-- Add remaining major developers and projects
-- This migration adds the most important remaining developers and their key projects

INSERT INTO projects (name, developer, region, available_leads, price_per_lead, description) VALUES

-- Inertia Egypt (Major developer)
('Vaya - Jefaira', 'Inertia Egypt', 'North Coast', 150, 42.00, 'Vaya development in Jefaira coastal project.'),
('Fifty 7', 'Inertia Egypt', 'New Cairo', 120, 34.00, 'Fifty 7 residential development.'),
('Furl', 'Inertia Egypt', 'New Cairo', 100, 35.00, 'Furl modern residential project.'),
('Quayside', 'Inertia Egypt', 'New Cairo', 140, 33.00, 'Quayside waterfront-themed development.'),
('Veranda Sahl Hasheesh', 'Inertia Egypt', 'Red Sea', 80, 50.00, 'Veranda development in Sahl Hasheesh.'),
('Diwa Veranda Sahl Hasheesh', 'Inertia Egypt', 'Red Sea', 70, 52.00, 'Diwa development in Veranda Sahl Hasheesh.'),
('BRIX', 'Inertia Egypt', 'New Cairo', 110, 36.00, 'BRIX modern residential development.'),
('Jefaira', 'Inertia Egypt', 'North Coast', 200, 40.00, 'Main Jefaira coastal development.'),
('Soleya', 'Inertia Egypt', 'North Coast', 130, 41.00, 'Soleya coastal residential project.'),
('The Cribs Jefaira', 'Inertia Egypt', 'North Coast', 90, 43.00, 'Cribs development in Jefaira.'),
('G Cribs', 'Inertia Egypt', 'New Cairo', 85, 37.00, 'G Cribs residential development.'),
('Joulz', 'Inertia Egypt', '6th of October', 180, 31.00, 'Joulz integrated community development.'),
('The Peak Joulz', 'Inertia Egypt', '6th of October', 100, 33.00, 'Peak development in Joulz project.'),
('Ayla Jefaira', 'Inertia Egypt', 'North Coast', 110, 42.00, 'Ayla development in Jefaira coastal project.'),

-- Misr Italia Properties (Major developer)
('B-Spaces Il Bosco City', 'Misr Italia Properties', 'New Capital', 120, 38.00, 'B-Spaces in Il Bosco City development.'),
('Hilltop Chalets - Solare', 'Misr Italia Properties', 'North Coast', 80, 48.00, 'Hilltop chalets in Solare coastal project.'),
('La Nuova Vista', 'Misr Italia Properties', 'New Capital', 140, 36.00, 'La Nuova Vista Italian-themed development.'),
('Cairo Business Park', 'Misr Italia Properties', 'New Capital', 100, 40.00, 'Business park development in New Capital.'),
('Allure Executive Offices', 'Misr Italia Properties', 'New Capital', 60, 45.00, 'Executive office development.'),
('Kai Sokhna', 'Misr Italia Properties', 'Ain Sokhna', 90, 42.00, 'Kai development in Ain Sokhna.'),
('Italian Square', 'Misr Italia Properties', 'New Capital', 80, 41.00, 'Italian-themed square development.'),
('The Creeks Villas', 'Misr Italia Properties', 'New Cairo', 70, 39.00, 'Creek-side villa development.'),
('The Park', 'Misr Italia Properties', 'New Capital', 150, 37.00, 'Park-themed development.'),
('B-Spaces', 'Misr Italia Properties', 'New Cairo', 110, 36.00, 'B-Spaces residential development.'),
('The Valley New Capital', 'Misr Italia Properties', 'New Capital', 160, 38.00, 'Valley development in New Capital.'),
('Sicily Lagoon', 'Misr Italia Properties', 'North Coast', 100, 46.00, 'Sicily-themed lagoon development.'),
('Radical 1', 'Misr Italia Properties', 'New Capital', 90, 39.00, 'Radical design residential development.'),
('The Cliff Il Bosco', 'Misr Italia Properties', 'New Capital', 80, 40.00, 'Cliff development in Il Bosco.'),
('Vinci Street', 'Misr Italia Properties', 'New Capital', 70, 41.00, 'Vinci-themed street development.'),
('Vinci', 'Misr Italia Properties', 'New Capital', 85, 40.00, 'Vinci residential development.'),
('Sila Il Bosco City', 'Misr Italia Properties', 'New Capital', 95, 39.00, 'Sila development in Il Bosco City.'),
('Solare', 'Misr Italia Properties', 'North Coast', 120, 45.00, 'Solare coastal development.'),
('THE MEADOWS Il Bosco', 'Misr Italia Properties', 'New Capital', 130, 38.00, 'Meadows development in Il Bosco.'),
('Il Bosco City', 'Misr Italia Properties', 'New Capital', 200, 37.00, 'Main Il Bosco City development.'),
('Il Bosco New Capital The Park', 'Misr Italia Properties', 'New Capital', 140, 38.00, 'Park development in Il Bosco New Capital.'),
('Il Bosco New Capital', 'Misr Italia Properties', 'New Capital', 250, 37.00, 'Main Il Bosco development in New Capital.'),

-- Tatweer Misr (Major developer)
('M Residence', 'Tatweer Misr', 'New Cairo', 130, 35.00, 'M Residence luxury development.'),
('Scenes', 'Tatweer Misr', 'New Cairo', 110, 36.00, 'Scenes residential development.'),
('Coflow', 'Tatweer Misr', 'New Cairo', 90, 37.00, 'Coflow modern residential project.'),
('The Lakes Villas Bloomfields', 'Tatweer Misr', 'New Cairo', 80, 40.00, 'Lake villas in Bloomfields development.'),
('Bloomfields', 'Tatweer Misr', 'New Cairo', 200, 35.00, 'Main Bloomfields development.'),
('Marina Residence Il Monte Galala', 'Tatweer Misr', 'Ain Sokhna', 100, 50.00, 'Marina residence in Il Monte Galala.'),
('The Vues Bloomfields', 'Tatweer Misr', 'New Cairo', 120, 36.00, 'Vues development in Bloomfields.'),
('Rivers', 'Tatweer Misr', 'New Cairo', 140, 34.00, 'River-themed residential development.'),
('Salt', 'Tatweer Misr', 'North Coast', 90, 45.00, 'Salt coastal development.'),
('PHIA Il Monte Galala', 'Tatweer Misr', 'Ain Sokhna', 70, 52.00, 'PHIA development in Il Monte Galala.'),
('Maesta, Il Monte Galala', 'Tatweer Misr', 'Ain Sokhna', 80, 51.00, 'Maesta development in Il Monte Galala.'),
('ISLA Il Monte Galala', 'Tatweer Misr', 'Ain Sokhna', 75, 53.00, 'ISLA development in Il Monte Galala.'),
('Fouka Bay', 'Tatweer Misr', 'North Coast', 150, 48.00, 'Fouka Bay coastal development.'),
('Il Monte Galala', 'Tatweer Misr', 'Ain Sokhna', 200, 50.00, 'Main Il Monte Galala development.'),
('Elara Il Monte Galala', 'Tatweer Misr', 'Ain Sokhna', 85, 52.00, 'Elara development in Il Monte Galala.'),
('Elva - Il Monte Galala', 'Tatweer Misr', 'Ain Sokhna', 90, 51.00, 'Elva development in Il Monte Galala.'),
('D-Bay', 'Tatweer Misr', 'North Coast', 160, 46.00, 'D-Bay coastal development.'),

-- City Edge Developments (Major developer)
('Downtown Extension', 'City Edge Developments', 'New Alamein', 120, 42.00, 'Downtown extension in New Alamein.'),
('Il Latini City Edge', 'City Edge Developments', 'North Coast', 90, 45.00, 'Italian-themed development by City Edge.'),
('Downtown New Alamein', 'City Edge Developments', 'New Alamein', 180, 40.00, 'Downtown development in New Alamein.'),
('Mamsha Vista', 'City Edge Developments', 'New Alamein', 140, 41.00, 'Vista development in Mamsha project.'),
('Jade Park', 'City Edge Developments', 'New Alamein', 100, 43.00, 'Jade-themed park development.'),
('Mazarine Townhouse', 'City Edge Developments', 'New Alamein', 80, 44.00, 'Townhouse development in Mazarine.'),
('Mazarine Ria', 'City Edge Developments', 'New Alamein', 70, 45.00, 'Ria development in Mazarine project.'),
('Mamsha Avenues', 'City Edge Developments', 'New Alamein', 110, 42.00, 'Avenues development in Mamsha.'),
('MWV-Mamsha Views', 'City Edge Developments', 'New Alamein', 95, 43.00, 'Mamsha Views development.'),
('Beach Front Towers', 'City Edge Developments', 'New Alamein', 60, 50.00, 'Beachfront tower development.'),
('Zahya', 'City Edge Developments', 'New Alamein', 200, 40.00, 'Main Zahya coastal development.'),
('New Garden City', 'City Edge Developments', 'New Capital', 150, 36.00, 'New Garden City development.'),
('Al Maqsad Park', 'City Edge Developments', 'New Alamein', 120, 41.00, 'Park development in Al Maqsad.'),
('North Edge New Alamein', 'City Edge Developments', 'New Alamein', 160, 40.00, 'Northern edge development in New Alamein.'),
('Mamsha Views', 'City Edge Developments', 'New Alamein', 130, 42.00, 'Views development in Mamsha project.'),
('Mamsha Gardens', 'City Edge Developments', 'New Alamein', 140, 41.00, 'Gardens development in Mamsha.'),
('Mamsha District', 'City Edge Developments', 'New Alamein', 180, 40.00, 'District development in Mamsha.'),
('Mamsha Almaqsad', 'City Edge Developments', 'New Alamein', 110, 42.00, 'Almaqsad development in Mamsha.'),
('Maspero Mall', 'City Edge Developments', 'New Capital', 50, 45.00, 'Maspero commercial mall development.'),
('Maspero Business Tower', 'City Edge Developments', 'New Capital', 40, 48.00, 'Maspero business tower.'),
('Mazarine Islands', 'City Edge Developments', 'New Alamein', 90, 46.00, 'Island development in Mazarine.'),
('Mazarine', 'City Edge Developments', 'New Alamein', 150, 43.00, 'Main Mazarine development.'),
('V40', 'City Edge Developments', 'New Capital', 80, 38.00, 'V40 residential development.'),
('The Gate - New Alamein', 'City Edge Developments', 'New Alamein', 100, 44.00, 'Gate development in New Alamein.'),
('Al Maqsad Residences', 'City Edge Developments', 'New Alamein', 120, 42.00, 'Residential development in Al Maqsad.'),
('Etapa', 'City Edge Developments', 'New Alamein', 90, 43.00, 'Etapa residential development.'),
('Al Maqsad', 'City Edge Developments', 'New Alamein', 200, 41.00, 'Main Al Maqsad development.'),
('Mazarine Commercial', 'City Edge Developments', 'New Alamein', 60, 47.00, 'Commercial development in Mazarine.'),

-- Al Marasem Development
('Lake Residence Fifth Square', 'Al Marasem Development', 'New Cairo', 120, 34.00, 'Lake residence in Fifth Square.'),
('Moon Residences', 'Al Marasem Development', 'New Cairo', 100, 35.00, 'Moon-themed residential development.'),
('Fifth SquareThe Mall', 'Al Marasem Development', 'New Cairo', 60, 38.00, 'Mall development in Fifth Square.'),
('Fifth Square Al Marasem', 'Al Marasem Development', 'New Cairo', 180, 33.00, 'Main Fifth Square development.'),
('Mar Ville', 'Al Marasem Development', 'North Coast', 90, 44.00, 'Mar Ville coastal development.'),
('Mar Bay - Ras El Hekma', 'Al Marasem Development', 'Ras El Hekma', 110, 48.00, 'Mar Bay development in Ras El Hekma.'),

-- Madaar Development
('Azha', 'Madaar Development', 'Ain Sokhna', 140, 45.00, 'Azha coastal development in Ain Sokhna.'),
('Azha North Coast', 'Madaar Development', 'North Coast', 160, 43.00, 'Azha development on North Coast.'),
('Valerie Village', 'Madaar Development', 'New Cairo', 90, 32.00, 'Valerie village residential development.'),
('Lilac Village', 'Madaar Development', 'New Cairo', 80, 33.00, 'Lilac-themed village development.'),
('Velais', 'Madaar Development', 'New Cairo', 70, 34.00, 'Velais residential development.'),
('Naos', 'Madaar Development', 'New Cairo', 85, 33.00, 'Naos modern residential project.'),
('Lacerta', 'Madaar Development', 'New Cairo', 75, 34.00, 'Lacerta residential development.'),
('AQ Residence', 'Madaar Development', 'New Cairo', 95, 32.00, 'AQ Residence development.'),
('Kastra', 'Madaar Development', 'New Cairo', 100, 31.00, 'Kastra residential development.'),
('Lunas', 'Madaar Development', 'New Cairo', 90, 32.00, 'Lunas residential project.'),
('Ogma', 'Madaar Development', 'New Cairo', 110, 31.00, 'Ogma residential development.'),

-- Al Ahly Sabbour Developments
('Youd', 'Al Ahly Sabbour Developments', 'New Cairo', 130, 33.00, 'Youd modern residential development.'),
('The Mornings', 'Al Ahly Sabbour Developments', 'New Cairo', 120, 34.00, 'Morning-themed residential development.'),
('Roofscape - At East', 'Al Ahly Sabbour Developments', 'New Cairo', 90, 36.00, 'Roofscape development in At East.'),
('At East', 'Al Ahly Sabbour Developments', 'New Cairo', 150, 35.00, 'At East residential development.'),
('Summer', 'Al Ahly Sabbour Developments', 'North Coast', 100, 42.00, 'Summer coastal development.'),
('Alaire', 'Al Ahly Sabbour Developments', 'New Cairo', 110, 34.00, 'Alaire residential development.'),
('The Square', 'Al Ahly Sabbour Developments', 'New Cairo', 140, 33.00, 'Square-themed development.'),
('Wood Walks', 'Al Ahly Sabbour Developments', 'New Cairo', 80, 35.00, 'Wood walk residential development.'),
('L Avenir', 'Al Ahly Sabbour Developments', 'New Cairo', 95, 36.00, 'L Avenir future-themed development.'),
('Amwaj', 'Al Ahly Sabbour Developments', 'North Coast', 120, 41.00, 'Amwaj wave-themed coastal development.'),
('Keeva', 'Al Ahly Sabbour Developments', 'New Cairo', 85, 35.00, 'Keeva residential development.'),
('Rare', 'Al Ahly Sabbour Developments', 'New Cairo', 70, 37.00, 'Rare exclusive residential development.'),
('The City Of Odyssia', 'Al Ahly Sabbour Developments', 'New Capital', 200, 38.00, 'Odyssia city development.'),
('The RIDGE Villas', 'Al Ahly Sabbour Developments', 'New Cairo', 60, 40.00, 'Ridge villa development.'),
('Green Square', 'Al Ahly Sabbour Developments', 'New Cairo', 130, 34.00, 'Green square development.'),
('Gaia', 'Al Ahly Sabbour Developments', 'North Coast', 110, 43.00, 'Gaia earth-themed coastal development.');

-- Update materialized view
REFRESH MATERIALIZED VIEW lead_analytics_mv;
