-- Insert All Real Estate Projects
-- This migration adds all the real estate projects with their developers

-- Clear existing projects first (optional - remove if you want to keep existing data)
-- DELETE FROM projects;

INSERT INTO projects (name, developer, region, available_leads, price_per_lead, description) VALUES
('Chess Field', 'Al Jazi Egypt', 'New Cairo', 100, 30.00, 'Premium development by Al Jazi Egypt'),
('Al Jazi First Marriott Residences', 'Al Jazi Egypt', 'New Cairo', 150, 45.00, 'Premium development by Al Jazi Egypt'),
('Al Jazi Gardens', 'Al Jazi Egypt', 'New Cairo', 100, 30.00, 'Premium development by Al Jazi Egypt'),
('The Ark', 'The Ark Development', 'New Cairo', 100, 30.00, 'Premium development by The Ark Development'),
('Paragon 1', 'Paragon Development', 'New Cairo', 100, 30.00, 'Premium development by Paragon Development'),
('Paragon 3', 'Paragon Development', 'New Cairo', 100, 30.00, 'Premium development by Paragon Development'),
('Paragon 2', 'Paragon Development', 'New Cairo', 100, 30.00, 'Premium development by Paragon Development'),
('Sector 2', 'Modad Development', 'New Cairo', 100, 30.00, 'Premium development by Modad Development'),
('Sector 1', 'Modad Development', 'New Cairo', 100, 30.00, 'Premium development by Modad Development'),
('El Patio Riva', 'La Vista Developments', 'New Cairo', 100, 30.00, 'Premium development by La Vista Developments'),
('Maliv Street', 'Kulture Developments', 'New Cairo', 100, 30.00, 'Premium development by Kulture Developments'),
('Maliv', 'Kulture Developments', 'New Cairo', 100, 30.00, 'Premium development by Kulture Developments'),
('Aroma', 'Aroma Development', 'New Cairo', 100, 30.00, 'Premium development by Aroma Development'),
('Sector 3', 'Modad Development', 'New Cairo', 100, 30.00, 'Premium development by Modad Development'),
('Doray', 'MBG Developments', 'New Cairo', 100, 30.00, 'Premium development by MBG Developments'),
('El Ashrafeya', 'El Ashrafeya', 'New Cairo', 100, 30.00, 'Premium development by El Ashrafeya'),
('Radix Agile', 'Radix Development', 'New Cairo', 100, 30.00, 'Premium development by Radix Development'),
('Ray Residence', 'Radix Development', 'New Cairo', 100, 30.00, 'Premium development by Radix Development'),
('Jirian - Palm Hills', 'Palm Hills Developments', 'New Cairo', 120, 38.00, 'Premium development by Palm Hills Developments'),
('Nile Business City', 'Nile Developments', 'New Capital', 0, 0.00, 'Premium development by Nile Developments'),
('Festival Tower', 'Nile Developments', 'New Capital', 0, 0.00, 'Premium development by Nile Developments'),
('Taycoon', 'Nile Developments', 'New Cairo', 100, 30.00, 'Premium development by Nile Developments'),
('31N Commercial Tower', 'Nile Developments', 'New Capital', 0, 0.00, 'Premium development by Nile Developments'),
('Valory Mall', 'Menassat Developments', 'New Capital', 0, 0.00, 'Premium development by Menassat Developments'),
('Podia Tower', 'Menassat Developments', 'New Capital', 0, 0.00, 'Premium development by Menassat Developments'),
('The Strip Mall', 'Town Writers', 'New Capital', 0, 0.00, 'Premium development by Town Writers'),
('88 Hub Mall', 'Town Writers', 'New Capital', 0, 0.00, 'Premium development by Town Writers'),
('Notion', 'Town Writers', 'New Cairo', 100, 30.00, 'Premium development by Town Writers'),
('Revolve Mall', 'Town Writers', 'New Capital', 0, 0.00, 'Premium development by Town Writers'),
('Central Point', 'Town Writers', 'New Cairo', 100, 30.00, 'Premium development by Town Writers'),
('The Willows', 'Roya Developments', 'New Cairo', 100, 30.00, 'Premium development by Roya Developments'),
('Selection', 'Roya Developments', 'New Cairo', 100, 30.00, 'Premium development by Roya Developments'),
('Telal Soul', 'Roya Developments', 'New Cairo', 100, 30.00, 'Premium development by Roya Developments'),
('Jamila', 'New Jersey Developments', 'New Cairo', 100, 30.00, 'Premium development by New Jersey Developments'),
('Al Karma 1', 'AlKarma Developments', 'New Cairo', 100, 30.00, 'Premium development by AlKarma Developments'),
('Al Karma Kay-Phase 2', 'AlKarma Developments', 'New Cairo', 100, 30.00, 'Premium development by AlKarma Developments'),
('Al Karma Kay-Phase 1', 'AlKarma Developments', 'New Cairo', 100, 30.00, 'Premium development by AlKarma Developments'),
('Begonia Residence', 'Menassat Developments', 'New Cairo', 100, 30.00, 'Premium development by Menassat Developments'),
('Katameya Gardens', 'North Africa For Real Estate Investment', 'New Cairo', 100, 30.00, 'Premium development by North Africa For Real Estate Investment'),
('Flow - Geo - The Med', 'People & Places', 'New Cairo', 100, 30.00, 'Premium development by People & Places'),
('Meadows-Sodic East', 'SODIC', 'New Cairo', 120, 38.00, 'Premium development by SODIC'),
('IVY', 'SODIC', 'New Cairo', 120, 38.00, 'Premium development by SODIC'),
('Beach Residence-June', 'SODIC', 'North Coast', 120, 40.00, 'Premium development by SODIC'),
('Aquamarine-June', 'SODIC', 'New Cairo', 120, 38.00, 'Premium development by SODIC'),
('Oak Residence', 'SODIC', 'New Cairo', 120, 38.00, 'Premium development by SODIC'),
('Golf Villas - Caesar', 'SODIC', 'New Cairo', 120, 38.00, 'Premium development by SODIC'),
('Camellia', 'SODIC', 'New Cairo', 120, 38.00, 'Premium development by SODIC'),
('Water Chalet - Ogami', 'SODIC', 'New Cairo', 120, 38.00, 'Premium development by SODIC'),
('Opal-June', 'SODIC', 'New Cairo', 120, 38.00, 'Premium development by SODIC'),
('Pearl-June', 'SODIC', 'New Cairo', 120, 38.00, 'Premium development by SODIC'),
('Bleu Vert', 'Saudi Egyptian Developers (SED)', 'New Cairo', 100, 30.00, 'Premium development by Saudi Egyptian Developers (SED)'),
('Central New Cairo', 'Saudi Egyptian Developers (SED)', 'New Cairo', 100, 30.00, 'Premium development by Saudi Egyptian Developers (SED)'),
('SVN Shades', 'ZG Developments', 'New Cairo', 100, 30.00, 'Premium development by ZG Developments'),
('Queen Land', 'Euphoria Group', 'New Cairo', 100, 30.00, 'Premium development by Euphoria Group'),
('De Joya 4', 'Taj Misr Developments', 'New Cairo', 100, 30.00, 'Premium development by Taj Misr Developments'),
('Ezdan', 'Taj Misr Developments', 'New Cairo', 100, 30.00, 'Premium development by Taj Misr Developments'),
('Taj Tower', 'Taj Misr Developments', 'New Capital', 0, 0.00, 'Premium development by Taj Misr Developments'),
('De Joya 2 Strip Mall', 'Taj Misr Developments', 'New Capital', 0, 0.00, 'Premium development by Taj Misr Developments'),
('De Joya 2', 'Taj Misr Developments', 'New Cairo', 100, 30.00, 'Premium development by Taj Misr Developments'),
('De Joya 1', 'Taj Misr Developments', 'New Cairo', 100, 30.00, 'Premium development by Taj Misr Developments'),
('De Joya', 'Taj Misr Developments', 'New Cairo', 100, 30.00, 'Premium development by Taj Misr Developments'),
('De Joya 3', 'Taj Misr Developments', 'New Cairo', 100, 30.00, 'Premium development by Taj Misr Developments'),
('De Joya 1 Strip Mall', 'Taj Misr Developments', 'New Capital', 0, 0.00, 'Premium development by Taj Misr Developments'),
('De Joya 3 Strip Mall', 'Taj Misr Developments', 'New Capital', 0, 0.00, 'Premium development by Taj Misr Developments'),
('Dejoya Villas', 'Taj Misr Developments', 'New Cairo', 100, 30.00, 'Premium development by Taj Misr Developments'),
('Dejoya Residence', 'Taj Misr Developments', 'New Cairo', 100, 30.00, 'Premium development by Taj Misr Developments'),
('Dejoya Park', 'Taj Misr Developments', 'New Cairo', 100, 30.00, 'Premium development by Taj Misr Developments'),
('De Joya Strip Mall', 'Taj Misr Developments', 'New Capital', 0, 0.00, 'Premium development by Taj Misr Developments'),
('Dejoya Primero Villas', 'Taj Misr Developments', 'New Cairo', 100, 30.00, 'Premium development by Taj Misr Developments'),
('Dejoya Plaza Residence', 'Taj Misr Developments', 'New Cairo', 0, 0.00, 'Premium development by Taj Misr Developments'),
('Moonreal Tower', 'Emaar Rezk Group Developments', 'New Capital', 0, 0.00, 'Premium development by Emaar Rezk Group Developments'),
('Eelaf Residence', 'Emaar Rezk Group Developments', 'New Cairo', 100, 30.00, 'Premium development by Emaar Rezk Group Developments'),
('Linwood', 'Emaar Rezk Group Developments', 'New Cairo', 100, 30.00, 'Premium development by Emaar Rezk Group Developments'),
('Kaya Plaza', 'First Group', 'New Cairo', 0, 0.00, 'Premium development by First Group'),
('IVY Residence', 'AGEC Developments', 'New Cairo', 100, 30.00, 'Premium development by AGEC Developments'),
('Kazan Plaza', 'First Group', 'New Cairo', 0, 0.00, 'Premium development by First Group'),
('Ritz New Zayed', 'ARQA Development Group', 'New Zayed', 100, 30.00, 'Premium development by ARQA Development Group'),
('Villa Mall New Capital', 'Better Home', 'New Capital', 0, 0.00, 'Premium development by Better Home'),
('Midtown New Cairo Mall', 'Better Home', 'New Capital', 0, 0.00, 'Premium development by Better Home'),
('Mazarine Commercial', 'City Edge Developments', 'New Capital', 0, 0.00, 'Premium development by City Edge Developments'),
('Rivette - Amwaj', 'Melee Development', 'New Cairo', 100, 30.00, 'Premium development by Melee Development'),
('Valerie Village', 'Madaar Development', 'New Cairo', 100, 30.00, 'Premium development by Madaar Development'),
('Lilac Village', 'Madaar Development', 'New Cairo', 100, 30.00, 'Premium development by Madaar Development'),
('Velais', 'Madaar Development', 'New Cairo', 100, 30.00, 'Premium development by Madaar Development'),
('Naos', 'Madaar Development', 'New Cairo', 100, 30.00, 'Premium development by Madaar Development'),
('Lacerta', 'Madaar Development', 'New Cairo', 100, 30.00, 'Premium development by Madaar Development'),
('AQ Residence', 'Madaar Development', 'New Cairo', 100, 30.00, 'Premium development by Madaar Development'),
('Kastra', 'Madaar Development', 'New Cairo', 100, 30.00, 'Premium development by Madaar Development'),
('Lunas', 'Madaar Development', 'New Cairo', 100, 30.00, 'Premium development by Madaar Development'),
('Azha', 'Madaar Development', 'New Cairo', 100, 30.00, 'Premium development by Madaar Development'),
('Azha North Coast', 'Madaar Development', 'North Coast', 120, 40.00, 'Premium development by Madaar Development'),
('Ogma', 'Madaar Development', 'New Cairo', 100, 30.00, 'Premium development by Madaar Development'),
('El Centro Business Complex', 'Empire State Developments', 'New Capital', 0, 0.00, 'Premium development by Empire State Developments'),
('Terraside Business Park', 'Brouq Developments', 'New Capital', 0, 0.00, 'Premium development by Brouq Developments'),
('Bling Capital Center', 'Brouq Developments', 'New Capital', 0, 0.00, 'Premium development by Brouq Developments'),
('Spark Capital Insights', 'Brouq Developments', 'New Capital', 100, 30.00, 'Premium development by Brouq Developments'),
('Alis', 'Melee Development', 'New Cairo', 100, 30.00, 'Premium development by Melee Development'),
('Pulse Green Square', 'Melee Development', 'New Cairo', 100, 30.00, 'Premium development by Melee Development'),
('Gaia Cabanas', 'Melee Development', 'New Cairo', 100, 30.00, 'Premium development by Melee Development'),
('Nmq', 'Melee Development', 'New Cairo', 100, 30.00, 'Premium development by Melee Development'),
('Pulse', 'Melee Development', 'New Cairo', 100, 30.00, 'Premium development by Melee Development'),
('Rouh Zayed', 'Al Amaken Developments', 'New Zayed', 100, 30.00, 'Premium development by Al Amaken Developments'),
('Waterside - Seashore', 'Hyde Park', 'North Coast', 120, 40.00, 'Premium development by Hyde Park'),
('Lake Side', 'Hyde Park', 'New Cairo', 100, 30.00, 'Premium development by Hyde Park'),
('Waterside', 'Hyde Park', 'New Cairo', 100, 30.00, 'Premium development by Hyde Park'),
('Garden Side', 'Hyde Park', 'New Cairo', 100, 30.00, 'Premium development by Hyde Park'),
('Town Island', 'Hyde Park', 'New Cairo', 100, 30.00, 'Premium development by Hyde Park'),
('Lagoon Town', 'Hyde Park', 'North Coast', 100, 30.00, 'Premium development by Hyde Park'),
('Grand Park', 'Hyde Park', 'New Cairo', 100, 30.00, 'Premium development by Hyde Park'),
('Shore Ville', 'Hyde Park', 'North Coast', 120, 40.00, 'Premium development by Hyde Park'),
('Park Residence - Garden Lakes', 'Hyde Park', 'New Cairo', 100, 30.00, 'Premium development by Hyde Park'),
('Central Residence - Hyde Park Central', 'Hyde Park', 'New Cairo', 100, 30.00, 'Premium development by Hyde Park'),
('Greens Residence New Cairo', 'Hyde Park', 'New Cairo', 100, 30.00, 'Premium development by Hyde Park'),
('Hyde Park Central', 'Hyde Park', 'New Cairo', 100, 30.00, 'Premium development by Hyde Park'),
('Parkway Residence - Hyde Park', 'Hyde Park', 'New Cairo', 100, 30.00, 'Premium development by Hyde Park'),
('Hyde Park', 'Hyde Park', 'New Cairo', 100, 30.00, 'Premium development by Hyde Park'),
('Hyde Park Business District', 'Hyde Park', 'New Capital', 0, 0.00, 'Premium development by Hyde Park'),
('Tawny', 'Hyde Park', 'New Cairo', 100, 30.00, 'Premium development by Hyde Park'),
('Garden Residence Hyde Park', 'Hyde Park', 'New Cairo', 100, 30.00, 'Premium development by Hyde Park'),
('Garden Lakes', 'Hyde Park', 'New Cairo', 100, 30.00, 'Premium development by Hyde Park'),
('Beach Chalets - Seashore', 'Hyde Park', 'North Coast', 120, 40.00, 'Premium development by Hyde Park'),
('Hyde Park North - Seashore', 'Hyde Park', 'North Coast', 120, 40.00, 'Premium development by Hyde Park'),
('Vigor', 'Al Baron Developments', 'New Cairo', 100, 30.00, 'Premium development by Al Baron Developments'),
('Bianchi Ilios', 'Al - Borouj Misr Developments Group (ABM)', 'New Cairo', 100, 30.00, 'Premium development by Al - Borouj Misr Developments Group (ABM)'),
('6ixty Heliopolis', 'Al - Borouj Misr Developments Group (ABM)', 'New Cairo', 100, 30.00, 'Premium development by Al - Borouj Misr Developments Group (ABM)'),
('FCC', 'Al - Borouj Misr Developments Group (ABM)', 'New Cairo', 100, 30.00, 'Premium development by Al - Borouj Misr Developments Group (ABM)'),
('Redwood Tower', 'A Capital Holding', 'New Capital', 0, 0.00, 'Premium development by A Capital Holding'),
('The Signature Tower', 'A Capital Holding', 'New Capital', 0, 0.00, 'Premium development by A Capital Holding'),
('Marriott Residences Heliopolis', 'A Capital Holding', 'New Cairo', 150, 45.00, 'Premium development by A Capital Holding'),
('Lake West 5', 'Cairo Capital Developments', 'New Cairo', 100, 30.00, 'Premium development by Cairo Capital Developments'),
('Lake West 4', 'Cairo Capital Developments', 'New Cairo', 100, 30.00, 'Premium development by Cairo Capital Developments'),
('Lake West', 'Cairo Capital Developments', 'New Cairo', 100, 30.00, 'Premium development by Cairo Capital Developments'),
('Grids New Cairo', 'Manaj Developments', 'New Cairo', 100, 30.00, 'Premium development by Manaj Developments'),
('Blanks', 'Manaj Developments', 'New Cairo', 100, 30.00, 'Premium development by Manaj Developments'),
('Aurora', 'Doja Development', 'New Cairo', 100, 30.00, 'Premium development by Doja Development'),
('Galini', 'Doja Development', 'New Cairo', 100, 30.00, 'Premium development by Doja Development'),
('Nest', 'N Developments', 'New Cairo', 100, 30.00, 'Premium development by N Developments'),
('Cyra - Sun Capital', 'Arabia Holding', 'New Capital', 100, 30.00, 'Premium development by Arabia Holding'),
('Elora', 'Arabia Holding', 'New Cairo', 100, 30.00, 'Premium development by Arabia Holding'),
('Sun Capital', 'Arabia Holding', 'New Capital', 100, 30.00, 'Premium development by Arabia Holding'),
('Bungalows', 'Arabia Holding', 'New Cairo', 100, 30.00, 'Premium development by Arabia Holding'),
('Galleria Mall', 'Arabia Holding', 'New Capital', 0, 0.00, 'Premium development by Arabia Holding'),
('Galleria', 'Arabia Holding', 'New Cairo', 100, 30.00, 'Premium development by Arabia Holding'),
('N90', 'Wealth Development', 'New Cairo', 100, 30.00, 'Premium development by Wealth Development'),
('Wingate North 90St.', 'Wealth Development', 'New Cairo', 100, 30.00, 'Premium development by Wealth Development'),
('Elev8 Mall', 'Wealth Development', 'New Capital', 0, 0.00, 'Premium development by Wealth Development'),
('IV Business Park', 'Wealth Development', 'New Capital', 0, 0.00, 'Premium development by Wealth Development'),
('Plaza Vida', 'Kayan Real Estate', 'New Cairo', 0, 0.00, 'Premium development by Kayan Real Estate'),
('Vida Residence', 'Kayan Real Estate', 'New Cairo', 100, 30.00, 'Premium development by Kayan Real Estate'),
('C''est La Vie', 'Kayan Real Estate', 'New Cairo', 100, 30.00, 'Premium development by Kayan Real Estate'),
('Ivory Plaza', 'Tamayoz Developments', 'New Cairo', 0, 0.00, 'Premium development by Tamayoz Developments'),
('The Lark Residence', 'Tamayoz Developments', 'New Cairo', 100, 30.00, 'Premium development by Tamayoz Developments'),
('The Lark Mall', 'Tamayoz Developments', 'New Capital', 0, 0.00, 'Premium development by Tamayoz Developments'),
('Madar Mall', 'Tamayoz Developments', 'New Capital', 0, 0.00, 'Premium development by Tamayoz Developments'),
('Bahja', 'Symphony Developments', 'New Cairo', 100, 30.00, 'Premium development by Symphony Developments'),
('Icon Garden', 'Style Home Development', 'New Cairo', 100, 30.00, 'Premium development by Style Home Development'),
('Jebal El Sokhna', 'PRE Developments', 'North Coast', 100, 38.00, 'Premium development by PRE Developments'),
('Stone Residence', 'PRE Developments', 'New Cairo', 100, 30.00, 'Premium development by PRE Developments'),
('Point 90 Mall', 'PRE Developments', 'New Capital', 0, 0.00, 'Premium development by PRE Developments'),
('The Brooks', 'PRE Developments', 'New Cairo', 100, 30.00, 'Premium development by PRE Developments'),
('Ivoire East', 'PRE Developments', 'New Cairo', 100, 30.00, 'Premium development by PRE Developments'),
('Ivoire West', 'PRE Developments', 'New Cairo', 100, 30.00, 'Premium development by PRE Developments'),
('Reve Du Nil', 'Nouvara Developments', 'New Cairo', 100, 30.00, 'Premium development by Nouvara Developments'),
('Blue Walk', 'Sky AD Developments', 'New Cairo', 100, 30.00, 'Premium development by Sky AD Developments'),
('Bluetree', 'Sky AD Developments', 'New Cairo', 100, 30.00, 'Premium development by Sky AD Developments'),
('Sky North', 'Sky AD Developments', 'New Cairo', 100, 30.00, 'Premium development by Sky AD Developments'),
('Residence Eight Sky Abu Dhabi', 'Sky AD Developments', 'New Cairo', 100, 30.00, 'Premium development by Sky AD Developments'),
('One Residence', 'Sky AD Developments', 'New Cairo', 100, 30.00, 'Premium development by Sky AD Developments'),
('Capital Avenue', 'Sky AD Developments', 'New Capital', 100, 30.00, 'Premium development by Sky AD Developments'),
('Rayhanna Avenue', 'Morshedy Group', 'New Cairo', 100, 30.00, 'Premium development by Morshedy Group'),
('Valencia Valley', 'NCB Developments', 'New Cairo', 100, 30.00, 'Premium development by NCB Developments'),
('Valencia Hub', 'NCB Developments', 'New Cairo', 0, 0.00, 'Premium development by NCB Developments'),
('Innoview Business Complex', 'NCB Developments', 'New Capital', 0, 0.00, 'Premium development by NCB Developments'),
('Villagio', 'Modon Egypt', 'New Cairo', 100, 30.00, 'Premium development by Modon Egypt'),
('The V Residence - Villagio', 'Modon Egypt', 'New Cairo', 100, 30.00, 'Premium development by Modon Egypt'),
('Lagoons Al Alamin', 'Modon Egypt', 'North Coast', 100, 30.00, 'Premium development by Modon Egypt'),
('Boutique Village', 'Modon Egypt', 'New Cairo', 100, 30.00, 'Premium development by Modon Egypt'),
('Jade & Blue', 'Aspect Development', 'New Cairo', 100, 30.00, 'Premium development by Aspect Development'),
('Moray', 'Main Marks', 'New Cairo', 100, 30.00, 'Premium development by Main Marks'),
('The Mornings', 'Al Ahly Sabbour Developments', 'New Cairo', 100, 30.00, 'Premium development by Al Ahly Sabbour Developments'),
('Roofscape - At East', 'Al Ahly Sabbour Developments', 'New Cairo', 100, 30.00, 'Premium development by Al Ahly Sabbour Developments'),
('At East', 'Al Ahly Sabbour Developments', 'New Cairo', 100, 30.00, 'Premium development by Al Ahly Sabbour Developments'),
('Summer', 'Al Ahly Sabbour Developments', 'New Cairo', 100, 30.00, 'Premium development by Al Ahly Sabbour Developments'),
('Alaire', 'Al Ahly Sabbour Developments', 'New Cairo', 100, 30.00, 'Premium development by Al Ahly Sabbour Developments'),
('The Square', 'Al Ahly Sabbour Developments', 'New Cairo', 100, 30.00, 'Premium development by Al Ahly Sabbour Developments'),
('Wood Walks', 'Al Ahly Sabbour Developments', 'New Cairo', 100, 30.00, 'Premium development by Al Ahly Sabbour Developments'),
('L''Avenir', 'Al Ahly Sabbour Developments', 'New Cairo', 100, 30.00, 'Premium development by Al Ahly Sabbour Developments'),
('Amwaj', 'Al Ahly Sabbour Developments', 'New Cairo', 100, 30.00, 'Premium development by Al Ahly Sabbour Developments'),
('Keeva', 'Al Ahly Sabbour Developments', 'New Cairo', 100, 30.00, 'Premium development by Al Ahly Sabbour Developments'),
('Rare', 'Al Ahly Sabbour Developments', 'New Cairo', 100, 30.00, 'Premium development by Al Ahly Sabbour Developments'),
('The City Of Odyssia', 'Al Ahly Sabbour Developments', 'New Cairo', 100, 30.00, 'Premium development by Al Ahly Sabbour Developments'),
('The RIDGE Villas', 'Al Ahly Sabbour Developments', 'New Cairo', 100, 30.00, 'Premium development by Al Ahly Sabbour Developments'),
('Green Square', 'Al Ahly Sabbour Developments', 'New Cairo', 100, 30.00, 'Premium development by Al Ahly Sabbour Developments'),
('Gaia', 'Al Ahly Sabbour Developments', 'New Cairo', 100, 30.00, 'Premium development by Al Ahly Sabbour Developments'),
('Youd', 'Al Ahly Sabbour Developments', 'New Cairo', 100, 30.00, 'Premium development by Al Ahly Sabbour Developments'),
('Jazal', 'Legacy Estates Developments', 'New Cairo', 100, 30.00, 'Premium development by Legacy Estates Developments'),
('CALA', 'Capital Link Developments', 'New Cairo', 100, 30.00, 'Premium development by Capital Link Developments'),
('Cattleya', 'Arabco Developments', 'New Cairo', 100, 30.00, 'Premium development by Arabco Developments'),
('The Harv', 'DAL Developments', 'New Cairo', 100, 30.00, 'Premium development by DAL Developments'),
('Thru Dal Developments', 'DAL Developments', 'New Cairo', 100, 30.00, 'Premium development by DAL Developments'),
('Five Fifty Five Business Complex', 'DAL Developments', 'New Capital', 0, 0.00, 'Premium development by DAL Developments'),
('Parkside Maadi Views', 'The Land Developers (TLD)', 'New Cairo', 100, 30.00, 'Premium development by The Land Developers (TLD)'),
('Jade-Il Bayou', 'The Land Developers (TLD)', 'North Coast', 120, 40.00, 'Premium development by The Land Developers (TLD)'),
('Armonia', 'The Land Developers (TLD)', 'New Cairo', 100, 30.00, 'Premium development by The Land Developers (TLD)'),
('Il Bayou', 'The Land Developers (TLD)', 'North Coast', 120, 40.00, 'Premium development by The Land Developers (TLD)'),
('Kukun', 'The Land Developers (TLD)', 'New Cairo', 100, 30.00, 'Premium development by The Land Developers (TLD)'),
('Sheraton Residence', 'Margins Development', 'New Cairo', 100, 30.00, 'Premium development by Margins Development'),
('Lusail Residence', 'Margins Development', 'New Cairo', 100, 30.00, 'Premium development by Margins Development'),
('Zia Business Complex', 'Margins Development', 'New Capital', 0, 0.00, 'Premium development by Margins Development'),
('Oaks Egypt', 'Margins Development', 'New Cairo', 100, 30.00, 'Premium development by Margins Development'),
('V Levels', 'Dunes Capital Group', 'New Cairo', 100, 30.00, 'Premium development by Dunes Capital Group'),
('The 8', 'El Gabry Developments', 'New Cairo', 100, 30.00, 'Premium development by El Gabry Developments'),
('Lac Ville', 'El Gabry Developments', 'New Cairo', 100, 30.00, 'Premium development by El Gabry Developments'),
('Majorelle', 'El Gabry Developments', 'New Cairo', 100, 30.00, 'Premium development by El Gabry Developments'),
('IRA', 'El Gabry Developments', 'New Cairo', 100, 30.00, 'Premium development by El Gabry Developments'),
('One50', 'El Gabry Developments', 'New Cairo', 100, 30.00, 'Premium development by El Gabry Developments'),
('The 8 Extension', 'El Gabry Developments', 'New Cairo', 100, 30.00, 'Premium development by El Gabry Developments'),
('Degla Towers', 'Morshedy Group', 'New Capital', 0, 0.00, 'Premium development by Morshedy Group'),
('Degla Palms', 'Morshedy Group', 'New Cairo', 100, 30.00, 'Premium development by Morshedy Group'),
('One Katameya', 'Morshedy Group', 'New Cairo', 100, 30.00, 'Premium development by Morshedy Group'),
('Crystal Plaza', 'Morshedy Group', 'New Cairo', 0, 0.00, 'Premium development by Morshedy Group'),
('Zahra Morshedy Group', 'Morshedy Group', 'New Cairo', 100, 30.00, 'Premium development by Morshedy Group'),
('Degla Land Mark', 'Morshedy Group', 'New Cairo', 100, 30.00, 'Premium development by Morshedy Group'),
('Skyline', 'Morshedy Group', 'New Cairo', 100, 30.00, 'Premium development by Morshedy Group'),
('Maadi Grand City', 'Morshedy Group', 'New Cairo', 100, 30.00, 'Premium development by Morshedy Group'),
('Lakefront', 'Morshedy Group', 'New Cairo', 100, 30.00, 'Premium development by Morshedy Group'),
('Bavaria Town', 'Morshedy Group', 'New Cairo', 100, 30.00, 'Premium development by Morshedy Group'),
('D View', 'Morshedy Group', 'New Cairo', 100, 30.00, 'Premium development by Morshedy Group'),
('Katameya Gate', 'Morshedy Group', 'New Cairo', 100, 30.00, 'Premium development by Morshedy Group'),
('Degla Landmark 2', 'Morshedy Group', 'New Cairo', 100, 30.00, 'Premium development by Morshedy Group'),
('Skyline-D', 'Morshedy Group', 'New Cairo', 100, 30.00, 'Premium development by Morshedy Group'),
('Degla Gardens', 'Morshedy Group', 'New Cairo', 100, 30.00, 'Premium development by Morshedy Group'),
('Mist', 'M Squared', 'New Cairo', 100, 30.00, 'Premium development by M Squared'),
('31 West', 'M Squared', 'New Cairo', 100, 30.00, 'Premium development by M Squared'),
('41 Business District', 'M Squared', 'New Capital', 0, 0.00, 'Premium development by M Squared'),
('El Masyaf', 'M Squared', 'New Cairo', 100, 30.00, 'Premium development by M Squared'),
('Trio', 'M Squared', 'New Cairo', 100, 30.00, 'Premium development by M Squared'),
('SQ1', 'Housing And Development Properties HDP', 'New Cairo', 100, 30.00, 'Premium development by Housing And Development Properties HDP'),
('Terrace', 'Housing And Development Properties HDP', 'New Cairo', 100, 30.00, 'Premium development by Housing And Development Properties HDP'),
('Talda', 'Housing And Development Properties HDP', 'New Cairo', 100, 30.00, 'Premium development by Housing And Development Properties HDP'),
('Club Hills Residence', 'Housing And Development Properties HDP', 'New Cairo', 100, 30.00, 'Premium development by Housing And Development Properties HDP'),
('The Gray', 'Housing And Development Properties HDP', 'New Cairo', 100, 30.00, 'Premium development by Housing And Development Properties HDP'),
('The Island - Marina 5', 'Housing And Development Properties HDP', 'North Coast', 120, 40.00, 'Premium development by Housing And Development Properties HDP'),
('Westview Residence', 'Housing And Development Properties HDP', 'New Cairo', 100, 30.00, 'Premium development by Housing And Development Properties HDP'),
('Al Burouj Smart Village', 'Imkan Misr', 'New Cairo', 100, 30.00, 'Premium development by Imkan Misr'),
('Al Burouj', 'Imkan Misr', 'New Cairo', 100, 30.00, 'Premium development by Imkan Misr'),
('Junction', 'Majid Al Futtaim', 'New Cairo', 100, 30.00, 'Premium development by Majid Al Futtaim'),
('T.Hub', 'Times Developments', 'New Cairo', 0, 0.00, 'Premium development by Times Developments'),
('Avelin Phase 2', 'Times Developments', 'New Cairo', 100, 30.00, 'Premium development by Times Developments'),
('Avelin', 'Times Developments', 'New Cairo', 100, 30.00, 'Premium development by Times Developments'),
('Coy Zayed', 'Voya Developments', 'New Zayed', 100, 30.00, 'Premium development by Voya Developments'),
('Zat', 'Voya Developments', 'New Cairo', 100, 30.00, 'Premium development by Voya Developments'),
('Parkside - Owest', 'Orascom Development Egypt', 'New Cairo', 100, 30.00, 'Premium development by Orascom Development Egypt'),
('Qemet Owest', 'Orascom Development Egypt', 'New Cairo', 100, 30.00, 'Premium development by Orascom Development Egypt'),
('O West Orascom', 'Orascom Development Egypt', 'New Cairo', 100, 30.00, 'Premium development by Orascom Development Egypt'),
('Makadi Heights', 'Orascom Development Egypt', 'New Cairo', 100, 30.00, 'Premium development by Orascom Development Egypt'),
('Zayard Avenue', 'Palmier Developments', 'New Cairo', 100, 30.00, 'Premium development by Palmier Developments'),
('Zayard Residence', 'Palmier Developments', 'New Cairo', 100, 30.00, 'Premium development by Palmier Developments'),
('Zayard Elite', 'Palmier Developments', 'New Cairo', 100, 30.00, 'Premium development by Palmier Developments'),
('Zayard Villa', 'Palmier Developments', 'New Cairo', 100, 30.00, 'Premium development by Palmier Developments'),
('Zayard North Strike', 'Palmier Developments', 'New Cairo', 100, 30.00, 'Premium development by Palmier Developments'),
('Park Central', 'Hassan Allam Properties', 'New Cairo', 100, 30.00, 'Premium development by Hassan Allam Properties'),
('Park View - Haptown', 'Hassan Allam Properties', 'New Cairo', 100, 30.00, 'Premium development by Hassan Allam Properties'),
('Haptown Park 227', 'Hassan Allam Properties', 'New Cairo', 100, 30.00, 'Premium development by Hassan Allam Properties'),
('Haptown Park 226', 'Hassan Allam Properties', 'New Cairo', 100, 30.00, 'Premium development by Hassan Allam Properties'),
('Haptown Park 254', 'Hassan Allam Properties', 'New Cairo', 100, 30.00, 'Premium development by Hassan Allam Properties'),
('HAPTown', 'Hassan Allam Properties', 'New Cairo', 100, 30.00, 'Premium development by Hassan Allam Properties'),
('The Great Lawn-Park Central', 'Hassan Allam Properties', 'New Cairo', 100, 30.00, 'Premium development by Hassan Allam Properties'),
('Swanlake Residences', 'Hassan Allam Properties', 'New Cairo', 100, 30.00, 'Premium development by Hassan Allam Properties'),
('Selina SwanLake Residences', 'Hassan Allam Properties', 'New Cairo', 100, 30.00, 'Premium development by Hassan Allam Properties'),
('Swan Lake West', 'Hassan Allam Properties', 'New Cairo', 100, 30.00, 'Premium development by Hassan Allam Properties'),
('Every SwanLake Residences Administrative', 'Hassan Allam Properties', 'New Capital', 100, 30.00, 'Premium development by Hassan Allam Properties'),
('The Scarlet SwanLake Residences', 'Hassan Allam Properties', 'New Cairo', 100, 30.00, 'Premium development by Hassan Allam Properties'),
('Swan Lake Residences Office Park', 'Hassan Allam Properties', 'New Cairo', 100, 30.00, 'Premium development by Hassan Allam Properties'),
('The Giselle SwanLake Residences', 'Hassan Allam Properties', 'New Cairo', 100, 30.00, 'Premium development by Hassan Allam Properties'),
('The Phoenix SwanLake Residences', 'Hassan Allam Properties', 'New Cairo', 100, 30.00, 'Premium development by Hassan Allam Properties'),
('IRIS SwanLake Residences', 'Hassan Allam Properties', 'New Cairo', 100, 30.00, 'Premium development by Hassan Allam Properties'),
('The Valleys', 'Hassan Allam Properties', 'New Cairo', 100, 30.00, 'Premium development by Hassan Allam Properties'),
('Jirian - Mountain View', 'Mountain View', 'New Cairo', 100, 30.00, 'Premium development by Mountain View'),
('Spring Fields Park', 'Mountain View', 'New Cairo', 100, 30.00, 'Premium development by Mountain View'),
('Plage', 'Mountain View', 'New Cairo', 100, 30.00, 'Premium development by Mountain View'),
('Club Park - Aliva', 'Mountain View', 'New Cairo', 100, 30.00, 'Premium development by Mountain View'),
('Lagoon Beach Park - Aliva', 'Mountain View', 'North Coast', 120, 40.00, 'Premium development by Mountain View'),
('Central Park - Aliva', 'Mountain View', 'New Cairo', 100, 30.00, 'Premium development by Mountain View'),
('Kings Way', 'Mountain View', 'New Cairo', 100, 30.00, 'Premium development by Mountain View'),
('HeartWork', 'Mountain View', 'New Cairo', 100, 30.00, 'Premium development by Mountain View'),
('Mountain View One', 'Mountain View', 'New Cairo', 100, 30.00, 'Premium development by Mountain View'),
('Mountain View Hyde Park', 'Mountain View', 'New Cairo', 100, 30.00, 'Premium development by Mountain View'),
('Mountain View Executive Residence Katameya', 'Mountain View', 'New Cairo', 100, 30.00, 'Premium development by Mountain View'),
('Mountain View Ras El Hekma', 'Mountain View', 'North Coast', 150, 45.00, 'Premium development by Mountain View'),
('Mountain View Giza Plateau', 'Mountain View', 'New Cairo', 100, 30.00, 'Premium development by Mountain View'),
('Mountain View Chillout Park', 'Mountain View', 'New Cairo', 100, 30.00, 'Premium development by Mountain View'),
('Mountain View Sokhna', 'Mountain View', 'North Coast', 100, 38.00, 'Premium development by Mountain View'),
('Mountain View ICity New Cairo', 'Mountain View', 'New Cairo', 100, 30.00, 'Premium development by Mountain View'),
('Mountain View ICity October', 'Mountain View', '6th of October', 100, 30.00, 'Premium development by Mountain View'),
('Mountain View October Park', 'Mountain View', '6th of October', 100, 30.00, 'Premium development by Mountain View'),
('Mountain View 4', 'Mountain View', 'New Cairo', 100, 30.00, 'Premium development by Mountain View'),
('Mountain View 2', 'Mountain View', 'New Cairo', 100, 30.00, 'Premium development by Mountain View'),
('Mountain View 1.1', 'Mountain View', 'New Cairo', 100, 30.00, 'Premium development by Mountain View'),
('LVLS Mountain View', 'Mountain View', 'New Cairo', 100, 30.00, 'Premium development by Mountain View'),
('Lagoon Beach Park Mountain View I City New Cairo', 'Mountain View', 'North Coast', 120, 40.00, 'Premium development by Mountain View'),
('Executive Residence Giza Plateau', 'Mountain View', 'New Cairo', 100, 30.00, 'Premium development by Mountain View'),
('Evia Mountain View', 'Mountain View', 'New Cairo', 100, 30.00, 'Premium development by Mountain View'),
('Aliva Mountain View Mostakbal City', 'Mountain View', 'New Cairo', 100, 30.00, 'Premium development by Mountain View'),
('Executive Residence New Cairo', 'Mountain View', 'New Cairo', 100, 30.00, 'Premium development by Mountain View'),
('Lagoon Beach Park Mountain View I-City October', 'Mountain View', 'North Coast', 120, 40.00, 'Premium development by Mountain View'),
('Crysta', 'Mountain View', 'New Cairo', 100, 30.00, 'Premium development by Mountain View'),
('MV Park - ICity New Cairo', 'Mountain View', 'New Cairo', 100, 30.00, 'Premium development by Mountain View'),
('Club Park- ICity New Cairo', 'Mountain View', 'New Cairo', 100, 30.00, 'Premium development by Mountain View'),
('Club Park - ICity October', 'Mountain View', '6th of October', 100, 30.00, 'Premium development by Mountain View'),
('Grand Valleys - Kayan City', 'Mountain View', 'New Cairo', 100, 30.00, 'Premium development by Mountain View'),
('Vaya - Jefaira', 'Inertia Egypt', 'New Cairo', 100, 30.00, 'Premium development by Inertia Egypt'),
('Fifty 7', 'Inertia Egypt', 'New Cairo', 100, 30.00, 'Premium development by Inertia Egypt'),
('Furl', 'Inertia Egypt', 'New Cairo', 100, 30.00, 'Premium development by Inertia Egypt'),
('Quayside', 'Inertia Egypt', 'New Cairo', 100, 30.00, 'Premium development by Inertia Egypt'),
('Veranda Sahl Hasheesh', 'Inertia Egypt', 'North Coast', 100, 30.00, 'Premium development by Inertia Egypt'),
('Diwa Veranda Sahl Hasheesh', 'Inertia Egypt', 'North Coast', 100, 30.00, 'Premium development by Inertia Egypt'),
('BRIX', 'Inertia Egypt', 'New Cairo', 100, 30.00, 'Premium development by Inertia Egypt'),
('Jefaira', 'Inertia Egypt', 'New Cairo', 100, 30.00, 'Premium development by Inertia Egypt'),
('Soleya', 'Inertia Egypt', 'New Cairo', 100, 30.00, 'Premium development by Inertia Egypt'),
('The Cribs Jefaira', 'Inertia Egypt', 'New Cairo', 100, 30.00, 'Premium development by Inertia Egypt'),
('G Cribs', 'Inertia Egypt', 'New Cairo', 100, 30.00, 'Premium development by Inertia Egypt'),
('Joulz', 'Inertia Egypt', 'New Cairo', 100, 30.00, 'Premium development by Inertia Egypt'),
('The Peak Joulz', 'Inertia Egypt', 'New Cairo', 100, 30.00, 'Premium development by Inertia Egypt'),
('Ayla Jefaira', 'Inertia Egypt', 'New Cairo', 100, 30.00, 'Premium development by Inertia Egypt'),
('Rosail', 'Khaled Sabry Holding', 'New Cairo', 100, 30.00, 'Premium development by Khaled Sabry Holding'),
('Stoda', 'IL Cazar Developments', 'New Cairo', 100, 30.00, 'Premium development by IL Cazar Developments'),
('Creektown', 'IL Cazar Developments', 'New Cairo', 100, 30.00, 'Premium development by IL Cazar Developments'),
('Creek District', 'IL Cazar Developments', 'New Cairo', 100, 30.00, 'Premium development by IL Cazar Developments'),
('The C', 'IL Cazar Developments', 'New Cairo', 100, 30.00, 'Premium development by IL Cazar Developments'),
('G-Haus - Glen', 'IL Cazar Developments', 'New Cairo', 100, 30.00, 'Premium development by IL Cazar Developments'),
('Westdays', 'IL Cazar Developments', 'New Cairo', 100, 30.00, 'Premium development by IL Cazar Developments'),
('Go Heliopolis', 'IL Cazar Developments', 'New Cairo', 100, 30.00, 'Premium development by IL Cazar Developments'),
('Safia - Ras El Hekma', 'IL Cazar Developments', 'North Coast', 150, 45.00, 'Premium development by IL Cazar Developments'),
('Glen', 'IL Cazar Developments', 'New Cairo', 100, 30.00, 'Premium development by IL Cazar Developments'),
('The Crest', 'IL Cazar Developments', 'New Cairo', 100, 30.00, 'Premium development by IL Cazar Developments'),
('Shamasi', 'SERAC Developments', 'New Cairo', 100, 30.00, 'Premium development by SERAC Developments'),
('City Hall 90', 'SERAC Developments', 'New Cairo', 100, 30.00, 'Premium development by SERAC Developments'),
('Gravity 7', 'Mercon Developments', 'New Cairo', 100, 30.00, 'Premium development by Mercon Developments'),
('Katameya Coast', 'Starlight Developments', 'North Coast', 100, 30.00, 'Premium development by Starlight Developments'),
('Katameya Creeks', 'Starlight Developments', 'New Cairo', 100, 30.00, 'Premium development by Starlight Developments'),
('Rivali', 'SAMCO Developments', 'New Cairo', 100, 30.00, 'Premium development by SAMCO Developments'),
('The Five', 'SAMCO Developments', 'New Cairo', 100, 30.00, 'Premium development by SAMCO Developments'),
('Centrada Plaza', 'Centrada Developments', 'New Cairo', 0, 0.00, 'Premium development by Centrada Developments'),
('West El Balad', 'Centrada Developments', 'New Cairo', 100, 30.00, 'Premium development by Centrada Developments'),
('Centrada Hub', 'Centrada Developments', 'New Cairo', 0, 0.00, 'Premium development by Centrada Developments'),
('Centrada One', 'Centrada Developments', 'New Cairo', 100, 30.00, 'Premium development by Centrada Developments'),
('Kite Complex', 'Centrada Developments', 'New Cairo', 100, 30.00, 'Premium development by Centrada Developments'),
('Kite', 'Centrada Developments', 'New Cairo', 100, 30.00, 'Premium development by Centrada Developments'),
('Zaha Park - New Capital', 'Home Town Developments', 'New Capital', 100, 30.00, 'Premium development by Home Town Developments'),
('Village', 'Home Town Developments', 'New Cairo', 100, 30.00, 'Premium development by Home Town Developments'),
('La Fayette Village', 'Home Town Developments', 'New Cairo', 100, 30.00, 'Premium development by Home Town Developments'),
('Udora Mall', 'Home Town Developments', 'New Capital', 0, 0.00, 'Premium development by Home Town Developments'),
('Home Residence', 'Home Town Developments', 'New Cairo', 100, 30.00, 'Premium development by Home Town Developments'),
('Glee', 'Tharaa Developements', 'New Cairo', 100, 30.00, 'Premium development by Tharaa Developements'),
('Pyramids Heights', 'ADD Properties', 'New Cairo', 100, 30.00, 'Premium development by ADD Properties'),
('Sky City', 'Pyramids Developments', 'New Cairo', 100, 30.00, 'Premium development by Pyramids Developments'),
('Pyramids City', 'Pyramids Developments', 'New Cairo', 100, 30.00, 'Premium development by Pyramids Developments'),
('Pyramids Mall', 'Pyramids Developments', 'New Capital', 0, 0.00, 'Premium development by Pyramids Developments'),
('Grand Square Mall', 'Pyramids Developments', 'New Capital', 0, 0.00, 'Premium development by Pyramids Developments'),
('Paris Mall', 'Pyramids Developments', 'New Capital', 0, 0.00, 'Premium development by Pyramids Developments'),
('La Capitale', 'Pyramids Developments', 'New Capital', 100, 30.00, 'Premium development by Pyramids Developments'),
('Pyramids Business Tower', 'Pyramids Developments', 'New Capital', 0, 0.00, 'Premium development by Pyramids Developments'),
('Champs Elysees Mall', 'Pyramids Developments', 'New Capital', 0, 0.00, 'Premium development by Pyramids Developments'),
('Rewaya', 'SIAC Developments', 'New Cairo', 100, 30.00, 'Premium development by SIAC Developments'),
('Noll', 'Kleek Developments', 'New Cairo', 100, 30.00, 'Premium development by Kleek Developments'),
('Palencia', 'K Developments', 'New Cairo', 100, 30.00, 'Premium development by K Developments'),
('Il Mondo Mall', 'Remal Developments', 'New Capital', 0, 0.00, 'Premium development by Remal Developments'),
('West Clay', 'Remal Developments', 'New Cairo', 100, 30.00, 'Premium development by Remal Developments'),
('Najma Walk', 'Eterna Development', 'New Cairo', 100, 30.00, 'Premium development by Eterna Development'),
('Elen New Cairo', 'Concrete Development', 'New Cairo', 100, 30.00, 'Premium development by Concrete Development'),
('Jadie Residence', 'Concrete Development', 'New Cairo', 100, 30.00, 'Premium development by Concrete Development'),
('Palm Island', 'TG Development', 'New Cairo', 100, 30.00, 'Premium development by TG Development'),
('Palm East For TG Developments', 'TG Development', 'New Cairo', 100, 30.00, 'Premium development by TG Development'),
('Annex 26 Business Complex', 'ARQA Development Group', 'New Capital', 0, 0.00, 'Premium development by ARQA Development Group'),
('I-Business Park', 'ARQA Development Group', 'New Capital', 0, 0.00, 'Premium development by ARQA Development Group'),
('Lumia Residence', 'Dubai Misr', 'New Cairo', 100, 30.00, 'Premium development by Dubai Misr'),
('Lumia Residence- New Capital', 'Dubai Misr', 'New Capital', 100, 30.00, 'Premium development by Dubai Misr'),
('Lumia Lagoons', 'Dubai Misr', 'North Coast', 100, 30.00, 'Premium development by Dubai Misr'),
('Capital Dubai Mall', 'Dubai Misr', 'New Capital', 0, 0.00, 'Premium development by Dubai Misr'),
('Obsidier', 'Dubai Misr', 'New Cairo', 100, 30.00, 'Premium development by Dubai Misr'),
('Serrano', 'New Plan', 'New Cairo', 100, 30.00, 'Premium development by New Plan'),
('Tonino Lamborghini Residences', 'New Plan', 'New Cairo', 100, 30.00, 'Premium development by New Plan'),
('Atika', 'New Plan', 'New Cairo', 100, 30.00, 'Premium development by New Plan'),
('Talah', 'New Plan', 'New Cairo', 100, 30.00, 'Premium development by New Plan'),
('Amara', 'New Plan', 'New Cairo', 100, 30.00, 'Premium development by New Plan'),
('Granvia Mall Serrano', 'New Plan', 'New Capital', 0, 0.00, 'Premium development by New Plan'),
('Eleven', 'New Plan', 'New Cairo', 100, 30.00, 'Premium development by New Plan'),
('Eclat', 'New Plan', 'New Cairo', 100, 30.00, 'Premium development by New Plan'),
('Jade Hills - City Gate', 'Qatari Diar', 'New Cairo', 100, 30.00, 'Premium development by Qatari Diar'),
('Sapphire Golf Residences', 'Qatari Diar', 'New Cairo', 100, 30.00, 'Premium development by Qatari Diar'),
('Sapphire Residence', 'Qatari Diar', 'New Cairo', 100, 30.00, 'Premium development by Qatari Diar'),
('City Gate', 'Qatari Diar', 'New Cairo', 100, 30.00, 'Premium development by Qatari Diar'),
('Park Valley Sova', 'Efid Development', 'New Cairo', 100, 30.00, 'Premium development by Efid Development'),
('Park Valley', 'Efid Development', 'New Cairo', 100, 30.00, 'Premium development by Efid Development'),
('Red (G) - Garnet', 'Jadeer Realestate', 'New Cairo', 100, 30.00, 'Premium development by Jadeer Realestate'),
('Garnet', 'Jadeer Realestate', 'New Cairo', 100, 30.00, 'Premium development by Jadeer Realestate'),
('Belva', 'Karnak Real Estate Developments', 'New Cairo', 100, 30.00, 'Premium development by Karnak Real Estate Developments'),
('Kasakuon - Eastville', 'Ajna Developments', 'New Cairo', 100, 30.00, 'Premium development by Ajna Developments'),
('Carnelia', 'Ajna Developments', 'New Cairo', 100, 30.00, 'Premium development by Ajna Developments'),
('Eastville', 'Ajna Developments', 'New Cairo', 100, 30.00, 'Premium development by Ajna Developments'),
('J East', 'Juzur Development', 'New Cairo', 100, 30.00, 'Premium development by Juzur Development'),
('Neo Business Park', 'Juzur Development', 'New Capital', 0, 0.00, 'Premium development by Juzur Development'),
('Zomra East', 'Nations Of Sky', 'New Cairo', 100, 30.00, 'Premium development by Nations Of Sky'),
('The Village Views', 'Ora Developers', 'New Cairo', 120, 38.00, 'Premium development by Ora Developers'),
('Park Side Residences', 'Ora Developers', 'New Cairo', 120, 38.00, 'Premium development by Ora Developers'),
('Club Residence', 'Ora Developers', 'New Cairo', 120, 38.00, 'Premium development by Ora Developers'),
('The Solos - Solana', 'Ora Developers', 'New Cairo', 120, 38.00, 'Premium development by Ora Developers'),
('The Emerald Collection - Zed East', 'Ora Developers', 'New Cairo', 120, 38.00, 'Premium development by Ora Developers'),
('Zed Tower', 'Ora Developers', 'New Capital', 0, 0.00, 'Premium development by Ora Developers'),
('Zed The U', 'Ora Developers', 'New Cairo', 120, 38.00, 'Premium development by Ora Developers'),
('ZED STRIP', 'Ora Developers', 'New Cairo', 120, 38.00, 'Premium development by Ora Developers'),
('Casa D''Or - Zed', 'Ora Developers', 'New Cairo', 120, 38.00, 'Premium development by Ora Developers'),
('Club Side Towers - Zed East', 'Ora Developers', 'New Capital', 0, 0.00, 'Premium development by Ora Developers'),
('ZED', 'Ora Developers', 'New Cairo', 120, 38.00, 'Premium development by Ora Developers'),
('ZED East', 'Ora Developers', 'New Cairo', 120, 38.00, 'Premium development by Ora Developers'),
('Solana', 'Ora Developers', 'New Cairo', 120, 38.00, 'Premium development by Ora Developers'),
('Acclaro - Silversands', 'Ora Developers', 'New Cairo', 120, 38.00, 'Premium development by Ora Developers'),
('Branded Residences - Silversands', 'Ora Developers', 'New Cairo', 120, 38.00, 'Premium development by Ora Developers'),
('Crystalline - Silversands', 'Ora Developers', 'New Cairo', 120, 38.00, 'Premium development by Ora Developers'),
('Silvertown Silversands', 'Ora Developers', 'New Cairo', 120, 38.00, 'Premium development by Ora Developers'),
('Silversands', 'Ora Developers', 'New Cairo', 120, 38.00, 'Premium development by Ora Developers'),
('The Islands', 'EGYGAB', 'New Cairo', 100, 30.00, 'Premium development by EGYGAB'),
('Granda Life', 'EGYGAB', 'New Cairo', 100, 30.00, 'Premium development by EGYGAB'),
('The Edge', 'EGYGAB', 'New Cairo', 100, 30.00, 'Premium development by EGYGAB'),
('Masaya', 'EGYGAB', 'New Cairo', 100, 30.00, 'Premium development by EGYGAB'),
('The Median Residences', 'EGYGAB', 'New Cairo', 100, 30.00, 'Premium development by EGYGAB'),
('Palm Beach Ain Sokhna', 'Lasirena Group', 'North Coast', 120, 40.00, 'Premium development by Lasirena Group'),
('Canan Capital', 'Lasirena Group', 'New Capital', 100, 30.00, 'Premium development by Lasirena Group'),
('Lasirena Bay', 'Lasirena Group', 'North Coast', 120, 40.00, 'Premium development by Lasirena Group'),
('Lasirena Sokhna Resort', 'Lasirena Group', 'North Coast', 100, 38.00, 'Premium development by Lasirena Group'),
('Lasirena Ras Sudr', 'Lasirena Group', 'New Cairo', 100, 30.00, 'Premium development by Lasirena Group'),
('Majesty Bay El Galala Lasirena', 'Lasirena Group', 'North Coast', 150, 45.00, 'Premium development by Lasirena Group'),
('Lasirena North Coast', 'Lasirena Group', 'North Coast', 120, 40.00, 'Premium development by Lasirena Group'),
('La Vento Oyoun Mousa', 'Lasirena Group', 'New Cairo', 100, 30.00, 'Premium development by Lasirena Group'),
('Lasirena Palm Beach', 'Lasirena Group', 'North Coast', 120, 40.00, 'Premium development by Lasirena Group'),
('Cape Bay Blumar Lasirena', 'Lasirena Group', 'North Coast', 120, 40.00, 'Premium development by Lasirena Group'),
('Naia Bay', 'Naia Developments', 'North Coast', 120, 40.00, 'Premium development by Naia Developments'),
('Naia West', 'Naia Developments', 'New Cairo', 100, 30.00, 'Premium development by Naia Developments'),
('Tadawy', 'Golden Pillars', 'New Cairo', 100, 30.00, 'Premium development by Golden Pillars'),
('Blue Sky Mall', 'History For Urban Development HUD', 'New Capital', 0, 0.00, 'Premium development by History For Urban Development HUD'),
('Blue Waters Mall', 'History For Urban Development HUD', 'New Capital', 0, 0.00, 'Premium development by History For Urban Development HUD'),
('Voke Mall', 'HPD- Heritage Pan Arab Development', 'New Capital', 0, 0.00, 'Premium development by HPD- Heritage Pan Arab Development'),
('Qamari', 'New Event Developments', 'New Cairo', 100, 30.00, 'Premium development by New Event Developments'),
('Allegria Residence', 'SODIC', '6th of October', 120, 38.00, 'Premium development by SODIC'),
('Villette', 'SODIC', 'New Cairo', 120, 38.00, 'Premium development by SODIC'),
('V Residences By Villette', 'SODIC', 'New Cairo', 120, 38.00, 'Premium development by SODIC'),
('Westown Medical Center', 'SODIC', '6th of October', 0, 0.00, 'Premium development by SODIC'),
('Westown The Portal', 'SODIC', '6th of October', 120, 38.00, 'Premium development by SODIC'),
('Eastown', 'SODIC', 'New Cairo', 120, 38.00, 'Premium development by SODIC'),
('One 16', 'SODIC', 'New Cairo', 120, 38.00, 'Premium development by SODIC'),
('VYE SODIC', 'SODIC', 'New Cairo', 120, 38.00, 'Premium development by SODIC'),
('Azailya', 'SODIC', 'New Cairo', 120, 38.00, 'Premium development by SODIC'),
('The Estates Residence', 'SODIC', 'New Cairo', 120, 38.00, 'Premium development by SODIC'),
('June', 'SODIC', 'New Cairo', 120, 38.00, 'Premium development by SODIC'),
('Sky Condos', 'SODIC', 'New Cairo', 120, 38.00, 'Premium development by SODIC'),
('Six West', 'SODIC', 'New Cairo', 120, 38.00, 'Premium development by SODIC'),
('Estates Residence - Nobu', 'SODIC', 'New Cairo', 120, 38.00, 'Premium development by SODIC'),
('The Estates', 'SODIC', 'New Cairo', 120, 38.00, 'Premium development by SODIC'),
('Sky Condos Phase 3, Villette', 'SODIC', 'New Cairo', 120, 38.00, 'Premium development by SODIC'),
('SODIC East', 'SODIC', 'New Cairo', 120, 38.00, 'Premium development by SODIC'),
('October Plaza', 'SODIC', '6th of October', 0, 0.00, 'Premium development by SODIC'),
('Eastown Residence', 'SODIC', 'New Cairo', 120, 38.00, 'Premium development by SODIC'),
('Caesar', 'SODIC', 'New Cairo', 120, 38.00, 'Premium development by SODIC'),
('Hazel - Sodic East', 'SODIC', 'New Cairo', 120, 38.00, 'Premium development by SODIC'),
('Karmell New Zayed', 'SODIC', 'New Zayed', 120, 38.00, 'Premium development by SODIC'),
('Eastown Administartive', 'SODIC', 'New Capital', 120, 38.00, 'Premium development by SODIC'),
('Ogami Ras El Hekma', 'SODIC', 'North Coast', 150, 45.00, 'Premium development by SODIC'),
('Safi Ras El Hekma', 'SODIC', 'North Coast', 150, 45.00, 'Premium development by SODIC'),
('Sodic Ras El Hekma', 'SODIC', 'North Coast', 150, 45.00, 'Premium development by SODIC'),
('West End', 'West End Developments', 'New Cairo', 100, 30.00, 'Premium development by West End Developments'),
('Triangle', 'The Waterway Developments', 'New Cairo', 100, 30.00, 'Premium development by The Waterway Developments'),
('Kairo', 'The Waterway Developments', 'New Cairo', 100, 30.00, 'Premium development by The Waterway Developments'),
('The Waterway - New Cairo', 'The Waterway Developments', 'New Cairo', 100, 30.00, 'Premium development by The Waterway Developments'),
('The Waterway North Coast', 'The Waterway Developments', 'North Coast', 120, 40.00, 'Premium development by The Waterway Developments'),
('WBR1', 'The Waterway Developments', 'New Cairo', 100, 30.00, 'Premium development by The Waterway Developments'),
('The Capitalway', 'The Waterway Developments', 'New Capital', 100, 30.00, 'Premium development by The Waterway Developments'),
('Solay', 'Living Yards Developments', 'New Cairo', 100, 30.00, 'Premium development by Living Yards Developments'),
('The Loft Plaza', 'Living Yards Developments', 'New Cairo', 0, 0.00, 'Premium development by Living Yards Developments'),
('Noir', 'Living Yards Developments', 'New Cairo', 100, 30.00, 'Premium development by Living Yards Developments'),
('The Loft', 'Living Yards Developments', 'New Cairo', 100, 30.00, 'Premium development by Living Yards Developments'),
('The Loft Capital Center Commercial', 'Living Yards Developments', 'New Capital', 0, 0.00, 'Premium development by Living Yards Developments'),
('Kayan', 'Arkan Palm Development', 'New Cairo', 100, 30.00, 'Premium development by Arkan Palm Development'),
('One33', 'Arkan Palm Development', 'New Cairo', 100, 30.00, 'Premium development by Arkan Palm Development'),
('205 Towers', 'Arkan Palm Development', 'New Capital', 0, 0.00, 'Premium development by Arkan Palm Development'),
('The Quad', 'Arkan Palm Development', 'New Cairo', 100, 30.00, 'Premium development by Arkan Palm Development'),
('The Angle', 'Arkan Palm Development', 'New Cairo', 100, 30.00, 'Premium development by Arkan Palm Development'),
('Waterfront Residence', 'Arkan Palm Development', 'New Cairo', 100, 30.00, 'Premium development by Arkan Palm Development'),
('205 Arkan Palm', 'Arkan Palm Development', 'New Cairo', 100, 30.00, 'Premium development by Arkan Palm Development'),
('Canal Walk Island', 'Arkan Palm Development', 'New Cairo', 100, 30.00, 'Premium development by Arkan Palm Development'),
('205 Safa Medical Complex', 'Arkan Palm Development', 'New Cairo', 0, 0.00, 'Premium development by Arkan Palm Development'),
('205 DownTown', 'Arkan Palm Development', 'New Cairo', 100, 30.00, 'Premium development by Arkan Palm Development'),
('Apex Business Complex', 'LUD -Lozan Urban Development', 'New Capital', 0, 0.00, 'Premium development by LUD -Lozan Urban Development'),
('The Rift Business Park', 'LUD -Lozan Urban Development', 'New Capital', 0, 0.00, 'Premium development by LUD -Lozan Urban Development'),
('Jazebeya', 'Upwyde Developments', 'New Cairo', 100, 30.00, 'Premium development by Upwyde Developments'),
('Sky Ramp', 'Upwyde Developments', 'New Cairo', 100, 30.00, 'Premium development by Upwyde Developments'),
('White Walk', 'Upwyde Developments', 'New Cairo', 100, 30.00, 'Premium development by Upwyde Developments'),
('White Residence', 'Upwyde Developments', 'New Cairo', 100, 30.00, 'Premium development by Upwyde Developments'),
('Cinco', 'Upwyde Developments', 'New Cairo', 100, 30.00, 'Premium development by Upwyde Developments'),
('Prk Vie', 'Upwyde Developments', 'New Cairo', 100, 30.00, 'Premium development by Upwyde Developments'),
('Granoy', 'Upwyde Developments', 'New Cairo', 100, 30.00, 'Premium development by Upwyde Developments'),
('It Business Hub', 'Upwyde Developments', 'New Capital', 0, 0.00, 'Premium development by Upwyde Developments'),
('Iguall', 'Upwyde Developments', 'New Cairo', 100, 30.00, 'Premium development by Upwyde Developments'),
('The Gryd', 'Upwyde Developments', 'New Cairo', 100, 30.00, 'Premium development by Upwyde Developments'),
('Lugano El Galala Ain El Sokhna', 'AOG Development', 'North Coast', 150, 45.00, 'Premium development by AOG Development'),
('Seazen', 'Al Qamzi Developments', 'North Coast', 100, 30.00, 'Premium development by Al Qamzi Developments'),
('Eastshire', 'Al Qamzi Developments', 'New Cairo', 100, 30.00, 'Premium development by Al Qamzi Developments'),
('Reel - Peerage', 'Al Riyadh Misr', 'New Cairo', 100, 30.00, 'Premium development by Al Riyadh Misr'),
('Peerage Residence', 'Al Riyadh Misr', 'New Cairo', 100, 30.00, 'Premium development by Al Riyadh Misr'),
('Z.Spot', 'Jiwa Developments', 'New Cairo', 100, 30.00, 'Premium development by Jiwa Developments'),
('One Plaza', 'Jiwa Developments', 'New Cairo', 0, 0.00, 'Premium development by Jiwa Developments'),
('Aiangle City Mall', 'Jiwa Developments', 'New Capital', 0, 0.00, 'Premium development by Jiwa Developments'),
('Regent''s Square', 'Al Dawlia Developments', 'New Cairo', 100, 30.00, 'Premium development by Al Dawlia Developments'),
('Menorca', 'MARDEV', 'New Cairo', 100, 30.00, 'Premium development by MARDEV'),
('Menorca Zayed', 'MARDEV', 'New Zayed', 100, 30.00, 'Premium development by MARDEV'),
('Skylight Mall New Capital', 'MARDEV', 'New Capital', 0, 0.00, 'Premium development by MARDEV'),
('Mardev Plaza New Capital', 'MARDEV', 'New Capital', 0, 0.00, 'Premium development by MARDEV'),
('Crescent Dream Land 6th October Zaya Development', 'Zaya Development', '6th of October', 100, 30.00, 'Premium development by Zaya Development'),
('Roudy', 'Zaya Development', 'New Cairo', 100, 30.00, 'Premium development by Zaya Development'),
('La Castle 7', 'Zaya Development', 'New Cairo', 100, 30.00, 'Premium development by Zaya Development'),
('Leaves', 'El Attal Holding', 'New Cairo', 100, 30.00, 'Premium development by El Attal Holding'),
('Golden Gate', 'Redcon For Offices And Commercial Centers', 'New Cairo', 100, 30.00, 'Premium development by Redcon For Offices And Commercial Centers'),
('M Residence', 'Tatweer Misr', 'New Cairo', 100, 30.00, 'Premium development by Tatweer Misr'),
('Scenes', 'Tatweer Misr', 'New Cairo', 100, 30.00, 'Premium development by Tatweer Misr'),
('Coflow', 'Tatweer Misr', 'New Cairo', 100, 30.00, 'Premium development by Tatweer Misr'),
('The Lakes Villas Bloomfields', 'Tatweer Misr', 'New Cairo', 100, 30.00, 'Premium development by Tatweer Misr'),
('Bloomfields', 'Tatweer Misr', 'New Cairo', 100, 30.00, 'Premium development by Tatweer Misr'),
('Marina Residence Il Monte Galala', 'Tatweer Misr', 'North Coast', 150, 45.00, 'Premium development by Tatweer Misr'),
('The Vues Bloomfields', 'Tatweer Misr', 'New Cairo', 100, 30.00, 'Premium development by Tatweer Misr'),
('Rivers', 'Tatweer Misr', 'New Cairo', 100, 30.00, 'Premium development by Tatweer Misr'),
('Salt', 'Tatweer Misr', 'New Cairo', 100, 30.00, 'Premium development by Tatweer Misr'),
('PHIA Il Monte Galala', 'Tatweer Misr', 'North Coast', 150, 45.00, 'Premium development by Tatweer Misr'),
('Maesta, Il Monte Galala', 'Tatweer Misr', 'North Coast', 150, 45.00, 'Premium development by Tatweer Misr'),
('ISLA Il Monte Galala', 'Tatweer Misr', 'North Coast', 150, 45.00, 'Premium development by Tatweer Misr'),
('Fouka Bay', 'Tatweer Misr', 'North Coast', 120, 40.00, 'Premium development by Tatweer Misr'),
('Il Monte Galala', 'Tatweer Misr', 'North Coast', 150, 45.00, 'Premium development by Tatweer Misr'),
('Elara Il Monte Galala', 'Tatweer Misr', 'North Coast', 150, 45.00, 'Premium development by Tatweer Misr'),
('Elva - Il Monte Galala', 'Tatweer Misr', 'North Coast', 150, 45.00, 'Premium development by Tatweer Misr'),
('D-Bay', 'Tatweer Misr', 'North Coast', 120, 40.00, 'Premium development by Tatweer Misr'),
('La Mirada', 'Grand Plaza For Real Estate And Touristic Development', 'New Cairo', 100, 30.00, 'Premium development by Grand Plaza For Real Estate And Touristic Development'),
('AMAZ BUSINESS COMPLEX', 'Al Fath Group', 'New Capital', 0, 0.00, 'Premium development by Al Fath Group'),
('Skybridge SIGNATURE HUB', 'Al Fath Group', 'New Cairo', 0, 0.00, 'Premium development by Al Fath Group'),
('Helio Eye', 'Al Fath Group', 'New Cairo', 100, 30.00, 'Premium development by Al Fath Group'),
('AEON Towers', 'Marakez', 'New Capital', 0, 0.00, 'Premium development by Marakez'),
('Crescent Walk', 'Marakez', 'New Cairo', 100, 30.00, 'Premium development by Marakez'),
('Mindhaus New Katameya', 'Marakez', 'New Cairo', 100, 30.00, 'Premium development by Marakez'),
('DISTRICT 5', 'Marakez', 'New Cairo', 100, 30.00, 'Premium development by Marakez'),
('Clubside Apartments District 5', 'Marakez', 'New Cairo', 100, 30.00, 'Premium development by Marakez'),
('Plateau District 5', 'Marakez', 'New Cairo', 100, 30.00, 'Premium development by Marakez'),
('D Parks New Cairo', 'Marakez', 'New Cairo', 100, 30.00, 'Premium development by Marakez'),
('Campus District 5', 'Marakez', 'New Cairo', 100, 30.00, 'Premium development by Marakez'),
('Crescent Walk East', 'Marakez', 'New Cairo', 100, 30.00, 'Premium development by Marakez'),
('Crescent Walk South', 'Marakez', 'New Cairo', 100, 30.00, 'Premium development by Marakez'),
('Central Avenue', 'Mabany Edris', 'New Cairo', 100, 30.00, 'Premium development by Mabany Edris'),
('Green IV October', 'Mabany Edris', '6th of October', 100, 30.00, 'Premium development by Mabany Edris'),
('Green 3', 'Mabany Edris', 'New Cairo', 100, 30.00, 'Premium development by Mabany Edris'),
('Green 5', 'Mabany Edris', 'New Cairo', 100, 30.00, 'Premium development by Mabany Edris'),
('Green 6', 'Mabany Edris', 'New Cairo', 100, 30.00, 'Premium development by Mabany Edris'),
('Koun', 'Mabany Edris', 'New Cairo', 100, 30.00, 'Premium development by Mabany Edris'),
('ONS', 'Mabany Edris', 'New Cairo', 100, 30.00, 'Premium development by Mabany Edris'),
('Rock Capital', 'Rock Developments', 'New Capital', 100, 30.00, 'Premium development by Rock Developments'),
('Rock Eden', 'Rock Developments', 'New Cairo', 100, 30.00, 'Premium development by Rock Developments'),
('Rock Vera', 'Rock Developments', 'New Cairo', 100, 30.00, 'Premium development by Rock Developments'),
('Rock White', 'Rock Developments', 'New Cairo', 100, 30.00, 'Premium development by Rock Developments'),
('Rock Gold', 'Rock Developments', 'New Cairo', 100, 30.00, 'Premium development by Rock Developments'),
('Monark Residence', 'Royal Development', 'New Cairo', 100, 30.00, 'Premium development by Royal Development'),
('Z View', 'Zodiac Development', 'New Cairo', 100, 30.00, 'Premium development by Zodiac Development'),
('Z90', 'Zodiac Development', 'New Cairo', 100, 30.00, 'Premium development by Zodiac Development'),
('Mizar Tower', 'Zodiac Development', 'New Capital', 0, 0.00, 'Premium development by Zodiac Development'),
('By 9 Mall', 'Al Rabat Developments', 'New Capital', 0, 0.00, 'Premium development by Al Rabat Developments'),
('B2555', 'Al Rabat Developments', 'New Cairo', 100, 30.00, 'Premium development by Al Rabat Developments'),
('Sleek', 'Al Rabat Developments', 'New Cairo', 100, 30.00, 'Premium development by Al Rabat Developments'),
('Sway', 'Al Rabat Developments', 'New Cairo', 100, 30.00, 'Premium development by Al Rabat Developments'),
('Space Mall', 'Gates Development', 'New Capital', 0, 0.00, 'Premium development by Gates Development'),
('Venia', 'Gates Development', 'New Cairo', 100, 30.00, 'Premium development by Gates Development'),
('Audaz', 'Gates Development', 'New Cairo', 100, 30.00, 'Premium development by Gates Development'),
('Catalan Mall', 'Gates Development', 'New Capital', 0, 0.00, 'Premium development by Gates Development'),
('Catalan', 'Gates Development', 'New Cairo', 100, 30.00, 'Premium development by Gates Development'),
('West Gate Business Hub', 'Gates Development', 'New Capital', 0, 0.00, 'Premium development by Gates Development'),
('Gates Prive', 'Gates Development', 'New Cairo', 100, 30.00, 'Premium development by Gates Development'),
('Lyv Caesar - Ras El Hekma', 'Gates Development', 'North Coast', 150, 45.00, 'Premium development by Gates Development'),
('Lugar', 'Gates Development', 'New Cairo', 100, 30.00, 'Premium development by Gates Development'),
('CIV West', 'Civilia Development', 'New Cairo', 100, 30.00, 'Premium development by Civilia Development'),
('Tru', 'UC Developments', 'New Cairo', 100, 30.00, 'Premium development by UC Developments'),
('Marqs', 'The Marq Communities', 'New Cairo', 100, 30.00, 'Premium development by The Marq Communities'),
('The Marq Ville', 'The Marq Communities', 'New Cairo', 100, 30.00, 'Premium development by The Marq Communities'),
('The Marq', 'The Marq Communities', 'New Cairo', 100, 30.00, 'Premium development by The Marq Communities'),
('Lakes The WonderMarq', 'The Marq Communities', 'New Cairo', 100, 30.00, 'Premium development by The Marq Communities'),
('Marquette Mostakbal City', 'The Marq Communities', 'New Cairo', 100, 30.00, 'Premium development by The Marq Communities'),
('Forest The WonderMarq', 'The Marq Communities', 'New Cairo', 100, 30.00, 'Premium development by The Marq Communities'),
('The Water Marq', 'The Marq Communities', 'New Cairo', 100, 30.00, 'Premium development by The Marq Communities'),
('The Marq Gardens', 'The Marq Communities', 'New Cairo', 100, 30.00, 'Premium development by The Marq Communities'),
('The WaterMarq', 'The Marq Communities', 'New Cairo', 100, 30.00, 'Premium development by The Marq Communities'),
('The Wonder Marq', 'The Marq Communities', 'New Cairo', 100, 30.00, 'Premium development by The Marq Communities'),
('Walk Of Cairo', 'Bonyan For Development And Trade', 'New Cairo', 100, 30.00, 'Premium development by Bonyan For Development And Trade'),
('Isola Centra', 'El Masria Group Developments', 'New Cairo', 100, 30.00, 'Premium development by El Masria Group Developments'),
('Isola Quattro', 'El Masria Group Developments', 'New Cairo', 100, 30.00, 'Premium development by El Masria Group Developments'),
('Isola October', 'El Masria Group Developments', '6th of October', 100, 30.00, 'Premium development by El Masria Group Developments'),
('Isola Villa', 'El Masria Group Developments', 'New Cairo', 100, 30.00, 'Premium development by El Masria Group Developments'),
('Isola Sheraton', 'El Masria Group Developments', 'New Cairo', 100, 30.00, 'Premium development by El Masria Group Developments'),
('Red', 'Cornerstone Development', 'New Cairo', 100, 30.00, 'Premium development by Cornerstone Development'),
('Cali Coast Ras El Hekma', 'MAVEN DEVELOPMENTS', 'North Coast', 150, 45.00, 'Premium development by MAVEN DEVELOPMENTS'),
('Baymount', 'MAVEN DEVELOPMENTS', 'North Coast', 120, 40.00, 'Premium development by MAVEN DEVELOPMENTS'),
('Acasa Mia', 'Dar Al Alamia Developments', 'New Cairo', 100, 30.00, 'Premium development by Dar Al Alamia Developments'),
('Ashgar Heights', 'IGI Real Estate', 'New Cairo', 100, 30.00, 'Premium development by IGI Real Estate'),
('Ashgar Residence', 'IGI Real Estate', 'New Cairo', 100, 30.00, 'Premium development by IGI Real Estate'),
('Ashgar City', 'IGI Real Estate', 'New Cairo', 100, 30.00, 'Premium development by IGI Real Estate'),
('Saada Commercial Hub', 'Horizon Egypt Development', 'New Capital', 0, 0.00, 'Premium development by Horizon Egypt Development'),
('Saada North Coast', 'Horizon Egypt Development', 'North Coast', 120, 40.00, 'Premium development by Horizon Egypt Development'),
('Saada Boutique', 'Horizon Egypt Development', 'New Cairo', 100, 30.00, 'Premium development by Horizon Egypt Development'),
('Saada', 'Horizon Egypt Development', 'New Cairo', 100, 30.00, 'Premium development by Horizon Egypt Development'),
('Moraya Residence', 'EDGESTONE Development And Real Estate', 'New Cairo', 100, 30.00, 'Premium development by EDGESTONE Development And Real Estate'),
('The View Waterway', 'The Waterway Developments', 'New Cairo', 100, 30.00, 'Premium development by The Waterway Developments'),
('W Signature', 'The Waterway Developments', 'New Cairo', 100, 30.00, 'Premium development by The Waterway Developments'),
('Ramla', 'Marakez', 'New Cairo', 100, 30.00, 'Premium development by Marakez'),
('Bella East', 'Al Manara Developments', 'New Cairo', 100, 30.00, 'Premium development by Al Manara Developments'),
('Bella Romance', 'Al Manara Developments', 'New Cairo', 100, 30.00, 'Premium development by Al Manara Developments'),
('Bella Vento', 'Al Manara Developments', 'New Cairo', 100, 30.00, 'Premium development by Al Manara Developments'),
('Direction White - Oyster', 'Arabella', 'New Cairo', 100, 30.00, 'Premium development by Arabella'),
('Direction White Phase One', 'Arabella', 'New Cairo', 100, 30.00, 'Premium development by Arabella'),
('Water Creek - Direction White', 'Arabella', 'New Cairo', 100, 30.00, 'Premium development by Arabella'),
('Direction White', 'Arabella', 'New Cairo', 100, 30.00, 'Premium development by Arabella'),
('Downtown Extension', 'City Edge Developments', 'New Cairo', 100, 30.00, 'Premium development by City Edge Developments'),
('Il Latini City Edge', 'City Edge Developments', 'New Cairo', 100, 30.00, 'Premium development by City Edge Developments'),
('Downtown New Alamein', 'City Edge Developments', 'New Cairo', 100, 30.00, 'Premium development by City Edge Developments'),
('Mamsha Vista', 'City Edge Developments', 'New Cairo', 100, 30.00, 'Premium development by City Edge Developments'),
('Jade Park', 'City Edge Developments', 'New Cairo', 100, 30.00, 'Premium development by City Edge Developments'),
('Mazarine Townhouse', 'City Edge Developments', 'New Cairo', 100, 30.00, 'Premium development by City Edge Developments'),
('Mazarine Ria', 'City Edge Developments', 'New Cairo', 100, 30.00, 'Premium development by City Edge Developments'),
('Mamsha Avenues', 'City Edge Developments', 'New Cairo', 100, 30.00, 'Premium development by City Edge Developments'),
('MWV-Mamsha Views', 'City Edge Developments', 'New Cairo', 100, 30.00, 'Premium development by City Edge Developments'),
('Beach Front Towers', 'City Edge Developments', 'North Coast', 0, 0.00, 'Premium development by City Edge Developments'),
('Zahya', 'City Edge Developments', 'New Cairo', 100, 30.00, 'Premium development by City Edge Developments'),
('New Garden City', 'City Edge Developments', 'New Cairo', 100, 30.00, 'Premium development by City Edge Developments'),
('Al Maqsad Park', 'City Edge Developments', 'New Cairo', 100, 30.00, 'Premium development by City Edge Developments'),
('North Edge New Alamein', 'City Edge Developments', 'New Cairo', 100, 30.00, 'Premium development by City Edge Developments'),
('Mamsha Views', 'City Edge Developments', 'New Cairo', 100, 30.00, 'Premium development by City Edge Developments'),
('Mamsha Gardens', 'City Edge Developments', 'New Cairo', 100, 30.00, 'Premium development by City Edge Developments'),
('Mamsha District', 'City Edge Developments', 'New Cairo', 100, 30.00, 'Premium development by City Edge Developments'),
('Mamsha Almaqsad', 'City Edge Developments', 'New Cairo', 100, 30.00, 'Premium development by City Edge Developments'),
('Maspero Mall', 'City Edge Developments', 'New Capital', 0, 0.00, 'Premium development by City Edge Developments'),
('Maspero Business Tower', 'City Edge Developments', 'New Capital', 0, 0.00, 'Premium development by City Edge Developments'),
('Mazarine Islands', 'City Edge Developments', 'New Cairo', 100, 30.00, 'Premium development by City Edge Developments'),
('Mazarine', 'City Edge Developments', 'New Cairo', 100, 30.00, 'Premium development by City Edge Developments'),
('V40', 'City Edge Developments', 'New Cairo', 100, 30.00, 'Premium development by City Edge Developments'),
('The Gate - New Alamein', 'City Edge Developments', 'New Cairo', 100, 30.00, 'Premium development by City Edge Developments'),
('Al Maqsad Residences', 'City Edge Developments', 'New Cairo', 100, 30.00, 'Premium development by City Edge Developments'),
('Etapa', 'City Edge Developments', 'New Cairo', 100, 30.00, 'Premium development by City Edge Developments'),
('Al Maqsad', 'City Edge Developments', 'New Cairo', 100, 30.00, 'Premium development by City Edge Developments'),
('Lake Residence Fifth Square', 'Al Marasem Development', 'New Cairo', 100, 30.00, 'Premium development by Al Marasem Development'),
('Moon Residences', 'Al Marasem Development', 'New Cairo', 100, 30.00, 'Premium development by Al Marasem Development'),
('Fifth SquareThe Mall', 'Al Marasem Development', 'New Capital', 0, 0.00, 'Premium development by Al Marasem Development'),
('Fifth Square Al Marasem', 'Al Marasem Development', 'New Cairo', 100, 30.00, 'Premium development by Al Marasem Development'),
('Mar Ville', 'Al Marasem Development', 'New Cairo', 100, 30.00, 'Premium development by Al Marasem Development'),
('Mar Bay - Ras El Hekma', 'Al Marasem Development', 'North Coast', 150, 45.00, 'Premium development by Al Marasem Development'),
('B-Spaces Il Bosco City', 'Misr Italia Properties', 'New Cairo', 100, 30.00, 'Premium development by Misr Italia Properties'),
('Hilltop Chalets - Solare', 'Misr Italia Properties', 'New Cairo', 100, 30.00, 'Premium development by Misr Italia Properties'),
('La Nuova Vista', 'Misr Italia Properties', 'New Cairo', 100, 30.00, 'Premium development by Misr Italia Properties'),
('Cairo Business Park', 'Misr Italia Properties', 'New Capital', 0, 0.00, 'Premium development by Misr Italia Properties'),
('Allure Executive Offices', 'Misr Italia Properties', 'New Cairo', 100, 30.00, 'Premium development by Misr Italia Properties'),
('Kai Sokhna', 'Misr Italia Properties', 'North Coast', 100, 38.00, 'Premium development by Misr Italia Properties'),
('Italian Square', 'Misr Italia Properties', 'New Cairo', 100, 30.00, 'Premium development by Misr Italia Properties'),
('The Creeks Villas', 'Misr Italia Properties', 'New Cairo', 100, 30.00, 'Premium development by Misr Italia Properties'),
('The Park', 'Misr Italia Properties', 'New Cairo', 100, 30.00, 'Premium development by Misr Italia Properties'),
('B-Spaces', 'Misr Italia Properties', 'New Cairo', 100, 30.00, 'Premium development by Misr Italia Properties'),
('The Valley New Capital', 'Misr Italia Properties', 'New Capital', 100, 30.00, 'Premium development by Misr Italia Properties'),
('Sicily Lagoon', 'Misr Italia Properties', 'North Coast', 100, 30.00, 'Premium development by Misr Italia Properties'),
('Radical 1', 'Misr Italia Properties', 'New Cairo', 100, 30.00, 'Premium development by Misr Italia Properties'),
('The Cliff Il Bosco', 'Misr Italia Properties', 'New Cairo', 100, 30.00, 'Premium development by Misr Italia Properties'),
('Vinci Street', 'Misr Italia Properties', 'New Cairo', 100, 30.00, 'Premium development by Misr Italia Properties'),
('Vinci', 'Misr Italia Properties', 'New Cairo', 100, 30.00, 'Premium development by Misr Italia Properties'),
('Sila Il Bosco City', 'Misr Italia Properties', 'New Cairo', 100, 30.00, 'Premium development by Misr Italia Properties'),
('Solare', 'Misr Italia Properties', 'New Cairo', 100, 30.00, 'Premium development by Misr Italia Properties'),
('THE MEADOWS Il Bosco', 'Misr Italia Properties', 'New Cairo', 100, 30.00, 'Premium development by Misr Italia Properties'),
('Il Bosco City', 'Misr Italia Properties', 'New Cairo', 100, 30.00, 'Premium development by Misr Italia Properties'),
('Il Bosco New Capital The Park', 'Misr Italia Properties', 'New Capital', 100, 30.00, 'Premium development by Misr Italia Properties'),
('Il Bosco New Capital', 'Misr Italia Properties', 'New Capital', 100, 30.00, 'Premium development by Misr Italia Properties'),
('D.O.S.E', 'Akam Alrajhi Developments', 'New Cairo', 100, 30.00, 'Premium development by Akam Alrajhi Developments'),
('Scenario', 'Akam Developments', 'New Cairo', 100, 30.00, 'Premium development by Akam Developments'),
('Ainava', 'Akam Developments', 'New Cairo', 100, 30.00, 'Premium development by Akam Developments'),
('Scene 7', 'Akam Developments', 'New Cairo', 100, 30.00, 'Premium development by Akam Developments'),
('W Residences Cairo', 'LMD', 'New Cairo', 100, 30.00, 'Premium development by LMD'),
('More Residences', 'LMD', 'New Cairo', 100, 30.00, 'Premium development by LMD'),
('Cairo Design District', 'LMD', 'New Cairo', 100, 30.00, 'Premium development by LMD'),
('Eastmed', 'LMD', 'New Cairo', 100, 30.00, 'Premium development by LMD'),
('There', 'LMD', 'New Cairo', 100, 30.00, 'Premium development by LMD'),
('Eastside', 'LMD', 'New Cairo', 100, 30.00, 'Premium development by LMD'),
('Zoya Ghazala Bay', 'LMD', 'North Coast', 120, 40.00, 'Premium development by LMD'),
('One - Ninety', 'LMD', 'New Cairo', 100, 30.00, 'Premium development by LMD'),
('Stei8ht', 'LMD', 'New Cairo', 100, 30.00, 'Premium development by LMD'),
('Three Sixty', 'LMD', 'New Cairo', 100, 30.00, 'Premium development by LMD'),
('Castle Landmark', 'Cred Developments', 'New Cairo', 100, 30.00, 'Premium development by Cred Developments'),
('Ever New Cairo', 'Cred Developments', 'New Cairo', 100, 30.00, 'Premium development by Cred Developments'),
('Ever West', 'Cred Developments', 'New Cairo', 100, 30.00, 'Premium development by Cred Developments'),
('Midtown New Zayed West', 'Better Home', 'New Zayed', 100, 30.00, 'Premium development by Better Home'),
('Midtown Sky', 'Better Home', 'New Cairo', 100, 30.00, 'Premium development by Better Home'),
('Midtown Solo', 'Better Home', 'New Cairo', 100, 30.00, 'Premium development by Better Home'),
('Midtown Condo Mall', 'Better Home', 'New Capital', 0, 0.00, 'Premium development by Better Home'),
('Cairo Business Plaza', 'Better Home', 'New Capital', 0, 0.00, 'Premium development by Better Home'),
('Midtown New Cairo', 'Better Home', 'New Cairo', 100, 30.00, 'Premium development by Better Home'),
('Midtown Condo', 'Better Home', 'New Cairo', 100, 30.00, 'Premium development by Better Home'),
('Highland Park', 'Better Home', 'New Cairo', 100, 30.00, 'Premium development by Better Home'),
('Midtown East', 'Better Home', 'New Cairo', 100, 30.00, 'Premium development by Better Home'),
('Midtown Solo Mall', 'Better Home', 'New Capital', 0, 0.00, 'Premium development by Better Home'),
('Midtown Sky Mall', 'Better Home', 'New Capital', 0, 0.00, 'Premium development by Better Home'),
('Midtown New Capital Villa', 'Better Home', 'New Capital', 100, 30.00, 'Premium development by Better Home'),
('London', 'JD Developments', 'New Cairo', 100, 30.00, 'Premium development by JD Developments'),
('Valea', 'Saudi Group Development', 'New Cairo', 100, 30.00, 'Premium development by Saudi Group Development'),
('El Patio Hills', 'La Vista Developments', 'New Cairo', 100, 30.00, 'Premium development by La Vista Developments'),
('El Patio 4', 'La Vista Developments', 'New Cairo', 100, 30.00, 'Premium development by La Vista Developments'),
('El Patio Town', 'La Vista Developments', 'New Cairo', 100, 30.00, 'Premium development by La Vista Developments'),
('D Line', 'La Vista Developments', 'New Cairo', 100, 30.00, 'Premium development by La Vista Developments'),
('El Patio 6 October', 'La Vista Developments', '6th of October', 100, 30.00, 'Premium development by La Vista Developments'),
('El Patio Vera', 'La Vista Developments', 'New Cairo', 100, 30.00, 'Premium development by La Vista Developments'),
('El Patio Sola', 'La Vista Developments', 'New Cairo', 100, 30.00, 'Premium development by La Vista Developments'),
('Patio 3', 'La Vista Developments', 'New Cairo', 100, 30.00, 'Premium development by La Vista Developments'),
('LA Vista 5', 'La Vista Developments', 'New Cairo', 100, 30.00, 'Premium development by La Vista Developments'),
('La Vista 3', 'La Vista Developments', 'New Cairo', 100, 30.00, 'Premium development by La Vista Developments'),
('La Vista 6', 'La Vista Developments', 'New Cairo', 100, 30.00, 'Premium development by La Vista Developments'),
('La Vista 1', 'La Vista Developments', 'New Cairo', 100, 30.00, 'Premium development by La Vista Developments'),
('LA Vista 4', 'La Vista Developments', 'New Cairo', 100, 30.00, 'Premium development by La Vista Developments'),
('La Vista Bay', 'La Vista Developments', 'North Coast', 120, 40.00, 'Premium development by La Vista Developments'),
('LA VISTA 2', 'La Vista Developments', 'New Cairo', 100, 30.00, 'Premium development by La Vista Developments'),
('El Patio Zahraa', 'La Vista Developments', 'New Cairo', 100, 30.00, 'Premium development by La Vista Developments'),
('La Vista Sol', 'La Vista Developments', 'New Cairo', 100, 30.00, 'Premium development by La Vista Developments'),
('La Vista Ray', 'La Vista Developments', 'New Cairo', 100, 30.00, 'Premium development by La Vista Developments'),
('La Vista Topaz', 'La Vista Developments', 'New Cairo', 100, 30.00, 'Premium development by La Vista Developments'),
('El Patio 5 East', 'La Vista Developments', 'New Cairo', 100, 30.00, 'Premium development by La Vista Developments'),
('El Patio 7', 'La Vista Developments', 'New Cairo', 100, 30.00, 'Premium development by La Vista Developments'),
('El Patio Oro', 'La Vista Developments', 'New Cairo', 100, 30.00, 'Premium development by La Vista Developments'),
('La Vista Ras El Hekma', 'La Vista Developments', 'North Coast', 150, 45.00, 'Premium development by La Vista Developments'),
('La Vista Cascada', 'La Vista Developments', 'New Cairo', 100, 30.00, 'Premium development by La Vista Developments'),
('La Vista Gardens', 'La Vista Developments', 'New Cairo', 100, 30.00, 'Premium development by La Vista Developments'),
('Lagoona - La Vista Ras El Hekma', 'La Vista Developments', 'North Coast', 150, 45.00, 'Premium development by La Vista Developments'),
('El Patio 2', 'La Vista Developments', 'New Cairo', 100, 30.00, 'Premium development by La Vista Developments'),
('La Vista 7', 'La Vista Developments', 'New Cairo', 100, 30.00, 'Premium development by La Vista Developments'),
('La Vista City', 'La Vista Developments', 'New Cairo', 100, 30.00, 'Premium development by La Vista Developments'),
('Patio Vida', 'La Vista Developments', 'New Cairo', 100, 30.00, 'Premium development by La Vista Developments'),
('Linea', 'La Vista Developments', 'New Cairo', 100, 30.00, 'Premium development by La Vista Developments'),
('El Patio Prime', 'La Vista Developments', 'New Cairo', 100, 30.00, 'Premium development by La Vista Developments'),
('El Patio Casa', 'La Vista Developments', 'New Cairo', 100, 30.00, 'Premium development by La Vista Developments'),
('La Vista Bay East', 'La Vista Developments', 'North Coast', 120, 40.00, 'Premium development by La Vista Developments'),
('El Patio 1', 'La Vista Developments', 'New Cairo', 100, 30.00, 'Premium development by La Vista Developments');