/**
 * Database Types
 * 
 * **DO NOT EDIT THIS FILE MANUALLY**
 * 
 * This file is auto-generated from the Supabase database schema.
 * To regenerate: npm run db:types
 * 
 * @module shared/types/database
 * @generated
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "13.0.4"
  }
  public: {
    Tables: {
      content: {
        Row: {
          audience: Json | null
          body: string | null
          content_type: string
          created_at: string
          created_by_profile_id: string | null
          cta: Json | null
          end_at: string | null
          feature_enabled: boolean | null
          feature_key: string | null
          id: string
          last_metrics_update: string | null
          media_type: string | null
          media_url: string | null
          metadata: Json | null
          metrics_summary: Json | null
          placement: string | null
          setting_key: string | null
          setting_value: Json | null
          start_at: string | null
          status: string
          title: string | null
          total_clicks: number | null
          total_impressions: number | null
          total_interactions: number | null
          total_views: number | null
          unique_viewers: number | null
          updated_at: string
        }
        Insert: {
          audience?: Json | null
          body?: string | null
          content_type: string
          created_at?: string
          created_by_profile_id?: string | null
          cta?: Json | null
          end_at?: string | null
          feature_enabled?: boolean | null
          feature_key?: string | null
          id?: string
          last_metrics_update?: string | null
          media_type?: string | null
          media_url?: string | null
          metadata?: Json | null
          metrics_summary?: Json | null
          placement?: string | null
          setting_key?: string | null
          setting_value?: Json | null
          start_at?: string | null
          status?: string
          title?: string | null
          total_clicks?: number | null
          total_impressions?: number | null
          total_interactions?: number | null
          total_views?: number | null
          unique_viewers?: number | null
          updated_at?: string
        }
        Update: {
          audience?: Json | null
          body?: string | null
          content_type?: string
          created_at?: string
          created_by_profile_id?: string | null
          cta?: Json | null
          end_at?: string | null
          feature_enabled?: boolean | null
          feature_key?: string | null
          id?: string
          last_metrics_update?: string | null
          media_type?: string | null
          media_url?: string | null
          metadata?: Json | null
          metrics_summary?: Json | null
          placement?: string | null
          setting_key?: string | null
          setting_value?: Json | null
          start_at?: string | null
          status?: string
          title?: string | null
          total_clicks?: number | null
          total_impressions?: number | null
          total_interactions?: number | null
          total_views?: number | null
          unique_viewers?: number | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "content_created_by_profile_id_fkey"
            columns: ["created_by_profile_id"]
            isOneToOne: false
            referencedRelation: "profile_wallets_consolidated"
            referencedColumns: ["profile_id"]
          },
          {
            foreignKeyName: "content_created_by_profile_id_fkey"
            columns: ["created_by_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      events: {
        Row: {
          action: string | null
          activity_type: string | null
          actor_profile_id: string | null
          ai_coach: string | null
          assignee_profile_id: string | null
          attachments: Json | null
          body: string | null
          completed_at: string | null
          context_id: string | null
          context_type: string | null
          created_at: string
          created_by_profile_id: string | null
          details: Json | null
          due_at: string | null
          entity_id: string | null
          entity_type: string | null
          event_category: string | null
          event_type: string
          filters: Json | null
          from_profile_id: string | null
          id: string
          ip_address: string | null
          label: string | null
          label_color: string | null
          lead_id: string | null
          log_level: string | null
          message_type: string | null
          metadata: Json | null
          notification_channels: string[] | null
          notification_status: string | null
          notification_url: string | null
          payload: Json | null
          profile_id: string | null
          read_at: string | null
          reason: string | null
          recommendation: string | null
          result_count: number | null
          sent_at: string | null
          stage: string | null
          summary: string | null
          support_issue: string | null
          support_priority: string | null
          support_status: string | null
          support_subject: string | null
          support_topic: string | null
          target_profile_id: string | null
          task_status: string | null
          task_type: string | null
          thread_id: string | null
          title: string | null
          to_profile_id: string | null
          top_units: Json | null
          updated_at: string
          user_agent: string | null
        }
        Insert: {
          action?: string | null
          activity_type?: string | null
          actor_profile_id?: string | null
          ai_coach?: string | null
          assignee_profile_id?: string | null
          attachments?: Json | null
          body?: string | null
          completed_at?: string | null
          context_id?: string | null
          context_type?: string | null
          created_at?: string
          created_by_profile_id?: string | null
          details?: Json | null
          due_at?: string | null
          entity_id?: string | null
          entity_type?: string | null
          event_category?: string | null
          event_type: string
          filters?: Json | null
          from_profile_id?: string | null
          id?: string
          ip_address?: string | null
          label?: string | null
          label_color?: string | null
          lead_id?: string | null
          log_level?: string | null
          message_type?: string | null
          metadata?: Json | null
          notification_channels?: string[] | null
          notification_status?: string | null
          notification_url?: string | null
          payload?: Json | null
          profile_id?: string | null
          read_at?: string | null
          reason?: string | null
          recommendation?: string | null
          result_count?: number | null
          sent_at?: string | null
          stage?: string | null
          summary?: string | null
          support_issue?: string | null
          support_priority?: string | null
          support_status?: string | null
          support_subject?: string | null
          support_topic?: string | null
          target_profile_id?: string | null
          task_status?: string | null
          task_type?: string | null
          thread_id?: string | null
          title?: string | null
          to_profile_id?: string | null
          top_units?: Json | null
          updated_at?: string
          user_agent?: string | null
        }
        Update: {
          action?: string | null
          activity_type?: string | null
          actor_profile_id?: string | null
          ai_coach?: string | null
          assignee_profile_id?: string | null
          attachments?: Json | null
          body?: string | null
          completed_at?: string | null
          context_id?: string | null
          context_type?: string | null
          created_at?: string
          created_by_profile_id?: string | null
          details?: Json | null
          due_at?: string | null
          entity_id?: string | null
          entity_type?: string | null
          event_category?: string | null
          event_type?: string
          filters?: Json | null
          from_profile_id?: string | null
          id?: string
          ip_address?: string | null
          label?: string | null
          label_color?: string | null
          lead_id?: string | null
          log_level?: string | null
          message_type?: string | null
          metadata?: Json | null
          notification_channels?: string[] | null
          notification_status?: string | null
          notification_url?: string | null
          payload?: Json | null
          profile_id?: string | null
          read_at?: string | null
          reason?: string | null
          recommendation?: string | null
          result_count?: number | null
          sent_at?: string | null
          stage?: string | null
          summary?: string | null
          support_issue?: string | null
          support_priority?: string | null
          support_status?: string | null
          support_subject?: string | null
          support_topic?: string | null
          target_profile_id?: string | null
          task_status?: string | null
          task_type?: string | null
          thread_id?: string | null
          title?: string | null
          to_profile_id?: string | null
          top_units?: Json | null
          updated_at?: string
          user_agent?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "events_actor_profile_id_fkey"
            columns: ["actor_profile_id"]
            isOneToOne: false
            referencedRelation: "profile_wallets_consolidated"
            referencedColumns: ["profile_id"]
          },
          {
            foreignKeyName: "events_actor_profile_id_fkey"
            columns: ["actor_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "events_assignee_profile_id_fkey"
            columns: ["assignee_profile_id"]
            isOneToOne: false
            referencedRelation: "profile_wallets_consolidated"
            referencedColumns: ["profile_id"]
          },
          {
            foreignKeyName: "events_assignee_profile_id_fkey"
            columns: ["assignee_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "events_created_by_profile_id_fkey"
            columns: ["created_by_profile_id"]
            isOneToOne: false
            referencedRelation: "profile_wallets_consolidated"
            referencedColumns: ["profile_id"]
          },
          {
            foreignKeyName: "events_created_by_profile_id_fkey"
            columns: ["created_by_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "events_from_profile_id_fkey"
            columns: ["from_profile_id"]
            isOneToOne: false
            referencedRelation: "profile_wallets_consolidated"
            referencedColumns: ["profile_id"]
          },
          {
            foreignKeyName: "events_from_profile_id_fkey"
            columns: ["from_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "events_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "events_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profile_wallets_consolidated"
            referencedColumns: ["profile_id"]
          },
          {
            foreignKeyName: "events_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "events_target_profile_id_fkey"
            columns: ["target_profile_id"]
            isOneToOne: false
            referencedRelation: "profile_wallets_consolidated"
            referencedColumns: ["profile_id"]
          },
          {
            foreignKeyName: "events_target_profile_id_fkey"
            columns: ["target_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "events_to_profile_id_fkey"
            columns: ["to_profile_id"]
            isOneToOne: false
            referencedRelation: "profile_wallets_consolidated"
            referencedColumns: ["profile_id"]
          },
          {
            foreignKeyName: "events_to_profile_id_fkey"
            columns: ["to_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      leads: {
        Row: {
          assigned_at: string | null
          assigned_to_id: string | null
          batch_id: string | null
          budget: number | null
          buyer_user_id: string | null
          client_email: string | null
          client_job_title: string | null
          client_name: string
          client_phone: string
          client_phone2: string | null
          client_phone3: string | null
          company_name: string | null
          cpl_price: number | null
          created_at: string
          feedback: string | null
          id: string
          integration_id: string | null
          is_sold: boolean
          last_contacted_at: string | null
          next_followup_at: string | null
          owner_id: string | null
          platform: string | null
          priority: string | null
          project_id: string
          sold_at: string | null
          source: string | null
          stage: string
          updated_at: string
          upload_user_id: string | null
        }
        Insert: {
          assigned_at?: string | null
          assigned_to_id?: string | null
          batch_id?: string | null
          budget?: number | null
          buyer_user_id?: string | null
          client_email?: string | null
          client_job_title?: string | null
          client_name: string
          client_phone: string
          client_phone2?: string | null
          client_phone3?: string | null
          company_name?: string | null
          cpl_price?: number | null
          created_at?: string
          feedback?: string | null
          id?: string
          integration_id?: string | null
          is_sold?: boolean
          last_contacted_at?: string | null
          next_followup_at?: string | null
          owner_id?: string | null
          platform?: string | null
          priority?: string | null
          project_id: string
          sold_at?: string | null
          source?: string | null
          stage?: string
          updated_at?: string
          upload_user_id?: string | null
        }
        Update: {
          assigned_at?: string | null
          assigned_to_id?: string | null
          batch_id?: string | null
          budget?: number | null
          buyer_user_id?: string | null
          client_email?: string | null
          client_job_title?: string | null
          client_name?: string
          client_phone?: string
          client_phone2?: string | null
          client_phone3?: string | null
          company_name?: string | null
          cpl_price?: number | null
          created_at?: string
          feedback?: string | null
          id?: string
          integration_id?: string | null
          is_sold?: boolean
          last_contacted_at?: string | null
          next_followup_at?: string | null
          owner_id?: string | null
          platform?: string | null
          priority?: string | null
          project_id?: string
          sold_at?: string | null
          source?: string | null
          stage?: string
          updated_at?: string
          upload_user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "leads_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "leads_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects_with_lead_counts"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          created_at: string
          email: string
          id: string
          is_banned: boolean
          last_login_at: string | null
          manager_id: string | null
          name: string
          phone: string | null
          phone_verified_at: string | null
          remember_token: string | null
          role: string
          updated_at: string
          wallet_balance: number
        }
        Insert: {
          created_at?: string
          email: string
          id: string
          is_banned?: boolean
          last_login_at?: string | null
          manager_id?: string | null
          name: string
          phone?: string | null
          phone_verified_at?: string | null
          remember_token?: string | null
          role?: string
          updated_at?: string
          wallet_balance?: number
        }
        Update: {
          created_at?: string
          email?: string
          id?: string
          is_banned?: boolean
          last_login_at?: string | null
          manager_id?: string | null
          name?: string
          phone?: string | null
          phone_verified_at?: string | null
          remember_token?: string | null
          role?: string
          updated_at?: string
          wallet_balance?: number
        }
        Relationships: [
          {
            foreignKeyName: "profiles_manager_id_fkey"
            columns: ["manager_id"]
            isOneToOne: false
            referencedRelation: "profile_wallets_consolidated"
            referencedColumns: ["profile_id"]
          },
          {
            foreignKeyName: "profiles_manager_id_fkey"
            columns: ["manager_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      projects: {
        Row: {
          auto_assign_rules: Json | null
          available_leads: number
          cover_image: string | null
          created_at: string
          description: string | null
          developer_id: string
          id: string
          name: string
          price_per_lead: number
          project_code: string | null
          region: string
        }
        Insert: {
          auto_assign_rules?: Json | null
          available_leads?: number
          cover_image?: string | null
          created_at?: string
          description?: string | null
          developer_id: string
          id?: string
          name: string
          price_per_lead?: number
          project_code?: string | null
          region: string
        }
        Update: {
          auto_assign_rules?: Json | null
          available_leads?: number
          cover_image?: string | null
          created_at?: string
          description?: string | null
          developer_id?: string
          id?: string
          name?: string
          price_per_lead?: number
          project_code?: string | null
          region?: string
        }
        Relationships: []
      }
      "salemate-inventory": {
        Row: {
          area: string | null
          building_number: string | null
          compound: string | null
          created_at: string
          currency: string | null
          developer: string | null
          finishing: string | null
          floor_number: number | null
          garden_area: number | null
          id: number
          image: string | null
          is_launch: boolean | null
          last_inventory_update: string | null
          number_of_bathrooms: number | null
          number_of_bedrooms: number | null
          offers: string | null
          original_unit_id: string | null
          payment_plans: string | null
          phase: string | null
          price_in_egp: number | null
          price_per_meter: number | null
          property_type: string | null
          ready_by: string | null
          roof_area: number | null
          sale_type: string | null
          unit_area: number | null
          unit_id: string | null
          unit_number: string | null
          updated_at: string
        }
        Insert: {
          area?: string | null
          building_number?: string | null
          compound?: string | null
          created_at?: string
          currency?: string | null
          developer?: string | null
          finishing?: string | null
          floor_number?: number | null
          garden_area?: number | null
          id?: number
          image?: string | null
          is_launch?: boolean | null
          last_inventory_update?: string | null
          number_of_bathrooms?: number | null
          number_of_bedrooms?: number | null
          offers?: string | null
          original_unit_id?: string | null
          payment_plans?: string | null
          phase?: string | null
          price_in_egp?: number | null
          price_per_meter?: number | null
          property_type?: string | null
          ready_by?: string | null
          roof_area?: number | null
          sale_type?: string | null
          unit_area?: number | null
          unit_id?: string | null
          unit_number?: string | null
          updated_at?: string
        }
        Update: {
          area?: string | null
          building_number?: string | null
          compound?: string | null
          created_at?: string
          currency?: string | null
          developer?: string | null
          finishing?: string | null
          floor_number?: number | null
          garden_area?: number | null
          id?: number
          image?: string | null
          is_launch?: boolean | null
          last_inventory_update?: string | null
          number_of_bathrooms?: number | null
          number_of_bedrooms?: number | null
          offers?: string | null
          original_unit_id?: string | null
          payment_plans?: string | null
          phase?: string | null
          price_in_egp?: number | null
          price_per_meter?: number | null
          property_type?: string | null
          ready_by?: string | null
          roof_area?: number | null
          sale_type?: string | null
          unit_area?: number | null
          unit_id?: string | null
          unit_number?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      system_data: {
        Row: {
          api_key: string | null
          api_secret: string | null
          attempt_count: number | null
          channel: string | null
          code_hash: string | null
          config: Json | null
          context: Json | null
          created_at: string
          data_category: string | null
          data_type: string
          description: string | null
          email: string | null
          entity_name: string | null
          entity_status: string | null
          entity_type: string | null
          expires_at: string | null
          id: string
          is_active: boolean | null
          logo_url: string | null
          metadata: Json | null
          phone_number: string | null
          profile_id: string | null
          session_token: string | null
          session_type: string | null
          status: string | null
          target: string | null
          updated_at: string
          verified: boolean | null
          verified_at: string | null
          website: string | null
        }
        Insert: {
          api_key?: string | null
          api_secret?: string | null
          attempt_count?: number | null
          channel?: string | null
          code_hash?: string | null
          config?: Json | null
          context?: Json | null
          created_at?: string
          data_category?: string | null
          data_type: string
          description?: string | null
          email?: string | null
          entity_name?: string | null
          entity_status?: string | null
          entity_type?: string | null
          expires_at?: string | null
          id?: string
          is_active?: boolean | null
          logo_url?: string | null
          metadata?: Json | null
          phone_number?: string | null
          profile_id?: string | null
          session_token?: string | null
          session_type?: string | null
          status?: string | null
          target?: string | null
          updated_at?: string
          verified?: boolean | null
          verified_at?: string | null
          website?: string | null
        }
        Update: {
          api_key?: string | null
          api_secret?: string | null
          attempt_count?: number | null
          channel?: string | null
          code_hash?: string | null
          config?: Json | null
          context?: Json | null
          created_at?: string
          data_category?: string | null
          data_type?: string
          description?: string | null
          email?: string | null
          entity_name?: string | null
          entity_status?: string | null
          entity_type?: string | null
          expires_at?: string | null
          id?: string
          is_active?: boolean | null
          logo_url?: string | null
          metadata?: Json | null
          phone_number?: string | null
          profile_id?: string | null
          session_token?: string | null
          session_type?: string | null
          status?: string | null
          target?: string | null
          updated_at?: string
          verified?: boolean | null
          verified_at?: string | null
          website?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "system_data_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profile_wallets_consolidated"
            referencedColumns: ["profile_id"]
          },
          {
            foreignKeyName: "system_data_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      team_members: {
        Row: {
          invitation_expires_at: string | null
          invitation_token: string | null
          invited_by: string | null
          invited_email: string | null
          joined_at: string | null
          left_at: string | null
          profile_id: string
          role: string
          status: string
          team_id: string
        }
        Insert: {
          invitation_expires_at?: string | null
          invitation_token?: string | null
          invited_by?: string | null
          invited_email?: string | null
          joined_at?: string | null
          left_at?: string | null
          profile_id: string
          role: string
          status?: string
          team_id: string
        }
        Update: {
          invitation_expires_at?: string | null
          invitation_token?: string | null
          invited_by?: string | null
          invited_email?: string | null
          joined_at?: string | null
          left_at?: string | null
          profile_id?: string
          role?: string
          status?: string
          team_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "team_members_invited_by_fkey"
            columns: ["invited_by"]
            isOneToOne: false
            referencedRelation: "profile_wallets_consolidated"
            referencedColumns: ["profile_id"]
          },
          {
            foreignKeyName: "team_members_invited_by_fkey"
            columns: ["invited_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "team_members_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profile_wallets_consolidated"
            referencedColumns: ["profile_id"]
          },
          {
            foreignKeyName: "team_members_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "team_members_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      teams: {
        Row: {
          created_at: string
          id: string
          name: string
          owner_profile_id: string
          team_type: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          name: string
          owner_profile_id: string
          team_type?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
          owner_profile_id?: string
          team_type?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "teams_owner_profile_id_fkey"
            columns: ["owner_profile_id"]
            isOneToOne: false
            referencedRelation: "profile_wallets_consolidated"
            referencedColumns: ["profile_id"]
          },
          {
            foreignKeyName: "teams_owner_profile_id_fkey"
            columns: ["owner_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      transactions: {
        Row: {
          admin_notes: string | null
          amount: number
          approved_at: string | null
          approved_by: string | null
          balance_after: number | null
          balance_before: number | null
          batch_id: string | null
          commerce_type: string | null
          commission_rate: number | null
          created_at: string
          currency: string
          description: string | null
          gateway_payment_intent_id: string | null
          id: string
          lead_id: string | null
          ledger_entry_type: string | null
          metadata: Json | null
          notes: string | null
          parent_transaction_id: string | null
          partner_id: string | null
          payment_method: string | null
          payment_operation_id: string | null
          processed_at: string | null
          profile_id: string
          project_id: string | null
          provider: string | null
          provider_transaction_id: string | null
          quantity: number | null
          receipt_file_name: string | null
          receipt_url: string | null
          reference_id: string | null
          reference_type: string | null
          rejected_reason: string | null
          requested_at: string | null
          running_balance: number | null
          status: string
          transaction_category: string | null
          transaction_sequence: number
          transaction_type: string
          updated_at: string
          validated_at: string | null
          validated_by: string | null
          wallet_id: string | null
        }
        Insert: {
          admin_notes?: string | null
          amount: number
          approved_at?: string | null
          approved_by?: string | null
          balance_after?: number | null
          balance_before?: number | null
          batch_id?: string | null
          commerce_type?: string | null
          commission_rate?: number | null
          created_at?: string
          currency?: string
          description?: string | null
          gateway_payment_intent_id?: string | null
          id?: string
          lead_id?: string | null
          ledger_entry_type?: string | null
          metadata?: Json | null
          notes?: string | null
          parent_transaction_id?: string | null
          partner_id?: string | null
          payment_method?: string | null
          payment_operation_id?: string | null
          processed_at?: string | null
          profile_id: string
          project_id?: string | null
          provider?: string | null
          provider_transaction_id?: string | null
          quantity?: number | null
          receipt_file_name?: string | null
          receipt_url?: string | null
          reference_id?: string | null
          reference_type?: string | null
          rejected_reason?: string | null
          requested_at?: string | null
          running_balance?: number | null
          status?: string
          transaction_category?: string | null
          transaction_sequence?: number
          transaction_type: string
          updated_at?: string
          validated_at?: string | null
          validated_by?: string | null
          wallet_id?: string | null
        }
        Update: {
          admin_notes?: string | null
          amount?: number
          approved_at?: string | null
          approved_by?: string | null
          balance_after?: number | null
          balance_before?: number | null
          batch_id?: string | null
          commerce_type?: string | null
          commission_rate?: number | null
          created_at?: string
          currency?: string
          description?: string | null
          gateway_payment_intent_id?: string | null
          id?: string
          lead_id?: string | null
          ledger_entry_type?: string | null
          metadata?: Json | null
          notes?: string | null
          parent_transaction_id?: string | null
          partner_id?: string | null
          payment_method?: string | null
          payment_operation_id?: string | null
          processed_at?: string | null
          profile_id?: string
          project_id?: string | null
          provider?: string | null
          provider_transaction_id?: string | null
          quantity?: number | null
          receipt_file_name?: string | null
          receipt_url?: string | null
          reference_id?: string | null
          reference_type?: string | null
          rejected_reason?: string | null
          requested_at?: string | null
          running_balance?: number | null
          status?: string
          transaction_category?: string | null
          transaction_sequence?: number
          transaction_type?: string
          updated_at?: string
          validated_at?: string | null
          validated_by?: string | null
          wallet_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "transactions_approved_by_fkey"
            columns: ["approved_by"]
            isOneToOne: false
            referencedRelation: "profile_wallets_consolidated"
            referencedColumns: ["profile_id"]
          },
          {
            foreignKeyName: "transactions_approved_by_fkey"
            columns: ["approved_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "transactions_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "transactions_parent_transaction_id_fkey"
            columns: ["parent_transaction_id"]
            isOneToOne: false
            referencedRelation: "transactions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "transactions_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profile_wallets_consolidated"
            referencedColumns: ["profile_id"]
          },
          {
            foreignKeyName: "transactions_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "transactions_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "transactions_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects_with_lead_counts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "transactions_validated_by_fkey"
            columns: ["validated_by"]
            isOneToOne: false
            referencedRelation: "profile_wallets_consolidated"
            referencedColumns: ["profile_id"]
          },
          {
            foreignKeyName: "transactions_validated_by_fkey"
            columns: ["validated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      profile_wallets_consolidated: {
        Row: {
          balance: number | null
          created_at: string | null
          currency: string | null
          profile_id: string | null
          updated_at: string | null
        }
        Insert: {
          balance?: never
          created_at?: never
          currency?: never
          profile_id?: string | null
          updated_at?: never
        }
        Update: {
          balance?: never
          created_at?: never
          currency?: never
          profile_id?: string | null
          updated_at?: never
        }
        Relationships: []
      }
      projects_with_lead_counts: {
        Row: {
          available_leads: number | null
          cover_image: string | null
          created_at: string | null
          description: string | null
          developer_id: string | null
          id: string | null
          name: string | null
          region: string | null
        }
        Relationships: []
      }
      team_hierarchy_consolidated: {
        Row: {
          joined_at: string | null
          left_at: string | null
          owner_profile_id: string | null
          profile_id: string | null
          role: string | null
          status: string | null
          team_id: string | null
          team_name: string | null
          team_type: string | null
        }
        Relationships: [
          {
            foreignKeyName: "team_members_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profile_wallets_consolidated"
            referencedColumns: ["profile_id"]
          },
          {
            foreignKeyName: "team_members_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "team_members_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "teams_owner_profile_id_fkey"
            columns: ["owner_profile_id"]
            isOneToOne: false
            referencedRelation: "profile_wallets_consolidated"
            referencedColumns: ["profile_id"]
          },
          {
            foreignKeyName: "teams_owner_profile_id_fkey"
            columns: ["owner_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      accept_team_invitation: {
        Args: { invitation_token: string }
        Returns: Json
      }
      add_to_wallet: {
        Args: { p_amount: number; p_description?: string; p_user_id: string }
        Returns: Json
      }
      approve_purchase_request:
        | { Args: { lead_quantity: number; request_id: string }; Returns: Json }
        | { Args: { request_id: string }; Returns: Json }
      approve_purchase_request_and_assign_leads: {
        Args: {
          p_admin_id: string
          p_admin_notes?: string
          p_request_id: string
        }
        Returns: Json
      }
      assign_leads_to_team_member: {
        Args: {
          p_assignee_id: string
          p_lead_ids: string[]
          p_manager_id: string
        }
        Returns: Json
      }
      assign_support_case_to_agent: {
        Args: { agent_id: string; case_id: string }
        Returns: undefined
      }
      backfill_profiles: { Args: never; Returns: number }
      can_access_lead: { Args: { l_id: string }; Returns: boolean }
      can_purchase_for: {
        Args: { purchaser_id: string; target_id: string }
        Returns: boolean
      }
      can_user_view: {
        Args: { target_id: string; viewer_id: string }
        Returns: boolean
      }
      cleanup_expired_invitations: { Args: never; Returns: number }
      create_lead_request: {
        Args: {
          p_price_per_lead: number
          p_project_id: string
          p_requested_quantity: number
          p_user_id: string
          p_user_notes?: string
        }
        Returns: string
      }
      deduct_from_wallet: {
        Args: { p_amount: number; p_description?: string; p_user_id: string }
        Returns: Json
      }
      get_accessible_leads: {
        Args: { for_user_id: string }
        Returns: {
          assigned_to_id: string
          buyer_user_id: string
          client_name: string
          client_phone: string
          created_at: string
          lead_id: string
          project_id: string
          stage: string
        }[]
      }
      get_first_admin_id: { Args: never; Returns: string }
      get_next_project_code: { Args: never; Returns: string }
      get_project_by_code: { Args: { p_code: string }; Returns: string }
      get_team_user_ids: { Args: { root_user_id: string }; Returns: string[] }
      get_user_tree: {
        Args: { root_user_id: string }
        Returns: {
          depth: number
          manager_id: string
          user_email: string
          user_id: string
          user_name: string
          user_phone: string
          user_role: string
        }[]
      }
      get_user_wallet_balance: { Args: { p_user_id: string }; Returns: number }
      get_wallet_balance: { Args: { p_profile_id: string }; Returns: number }
      hash_otp: { Args: { code: string }; Returns: string }
      internal_adjust_wallet: {
        Args: {
          p_context: string
          p_delta: number
          p_description: string
          p_metadata?: Json
          p_reference?: string
          p_user_id: string
        }
        Returns: Json
      }
      is_admin: { Args: { user_id: string }; Returns: boolean }
      is_user_role: {
        Args: { allowed_roles: string[]; user_id: string }
        Returns: boolean
      }
      process_payment_and_topup: {
        Args: {
          p_error?: string
          p_gateway_transaction_id?: string
          p_status: string
          p_transaction_id: string
        }
        Returns: Json
      }
      purge_expired_otps: { Args: never; Returns: undefined }
      refresh_project_available_leads: {
        Args: { p_project: string }
        Returns: undefined
      }
      reject_team_invitation: {
        Args: { invitation_token: string }
        Returns: Json
      }
      rpc_approve_request: {
        Args: { p_admin_notes?: string; p_request: string }
        Returns: {
          leads_assigned: number
        }[]
      }
      rpc_calculate_order_total: {
        Args: { p_project: string; p_qty: number }
        Returns: number
      }
      rpc_reject_request: {
        Args: { p_admin_notes?: string; p_request: string }
        Returns: undefined
      }
      rpc_start_order: {
        Args: {
          p_payment: Database["public"]["Enums"]["payment_method"]
          p_project: string
          p_qty: number
          p_receipt_name?: string
          p_receipt_url: string
        }
        Returns: string
      }
      rpc_team_user_ids: {
        Args: { p_manager: string }
        Returns: {
          user_id: string
        }[]
      }
      rpc_upload_leads: {
        Args: { leads_data: Json; project_id: string }
        Returns: Json
      }
      unassign_leads: {
        Args: { p_lead_ids: string[]; p_manager_id: string }
        Returns: Json
      }
      update_project_lead_counts: { Args: never; Returns: undefined }
      update_wallet_balance: {
        Args: {
          p_amount: number
          p_description?: string
          p_reference_id?: string
          p_transaction_type: string
          p_user_id: string
        }
        Returns: string
      }
    }
    Enums: {
      order_status: "pending" | "approved" | "rejected"
      payment_method: "Instapay" | "VodafoneCash" | "BankTransfer"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      order_status: ["pending", "approved", "rejected"],
      payment_method: ["Instapay", "VodafoneCash", "BankTransfer"],
    },
  },
} as const
